<template>
    <div>
        <div class="container pt-100">
            <div class="user_profile_page">
                <div class="row">
                    <div class="col-md-8 center-col">
                        <div class="row">
                            <div class="col-md-3">
                                <div class="user_profile_img">
                                    <img v-if="user.avatar_url" :src="user.avatar_url" alt="">
                                    <img v-else src="/images/user-img.jpg" alt="">
                                </div>
                            </div>
                            <div class="col-md-9">
                                <div class="user_des">
                                    <h3 class="user_profile_name"> {{user.full_name}} <span @click="addDoubtModal"><i class="fas fa-edit"></i></span></h3>
                                    <p>{{user.introduction}}</p>
                                    <p>This data is generated by your interaction with posts,hence the more you interect
                                        with posts the more
                                        precise this data is. Currently we don't have enough data to analys your
                                        interest.
                                        Please share at least 3 Posts to generate this data.</p>
                                </div>
                                <div class="user_social_links">
                                    <div class="user_social_link_left">
                                        <span><i class="fab fa-facebook-f"></i></span>
                                        <span><i class="fab fa-linkedin"></i></span>
                                        <span><i class="fab fa-instagram"></i></span>
                                        <span><i class="fab fa-twitter"></i></span>

                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="user_interest">
                    <h4>Your Interest</h4>
                    <div class="user_int">
                        <div class="user_int_text">
                            <p>This data is generated by your interaction with posts,hence the more you interect with
                                posts the more
                                precise this data is.</p>
                            <p v-if="interests.length===0">Currently we don't have enough data to analys your interest.
                                Please share at least 3 Posts to generate this data.</p>
                        </div>
                        <div class="progess_bar">
                        <div class="cojl" v-for="(interest,index) in interests" :key="index">
                            <radial-progress-bar :diameter="150" :completed-steps="interest.percent" :total-steps="100"
                                :startColor="'#3746c5'" :stopColor="'#3746c5'" :innerStrokeColor="'#babee4'">
                                <p>{{ interest.percent }}%</p>
                                <p>{{ interest.name }}</p>
                            </radial-progress-bar>
                        </div>
                        </div> 
                    </div>
                </div>
            </div>

        </div>
        <modal name="add_doubt_modal" class="doubt_model">

            <form @submit.prevent="saveProfile">
                <div class="model_box_inner">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="model_input">
                                <label>Email Id</label>
                                <input class="form-control" type="text" placeholder="Enter Your Doubt" v-model="email">
                            </div>
                        </div>
                        <div class="col-md-12">
                            <div class="model_input">
                                <label>Facebook id Url</label>
                                <input class="form-control" type="text" v-model="fb_url"
                                    placeholder="Enter Your Subject">
                            </div>
                        </div>
                        <div class="col-md-12">
                            <div class="model_input">
                                <label>Instagram id Url</label>
                                <input class="form-control" type="text" v-model="insta_url"
                                    placeholder="Enter Your Subject">
                            </div>
                        </div>
                        <div class="col-md-12">
                            <div class="model_input">
                                <label>Linkedin id Url</label>
                                <input class="form-control" type="text" v-model="linked_url"
                                    placeholder="Enter Your Subject">
                            </div>
                        </div>
                        <div class="col-md-12">
                            <div class="user_edit_profile_img">
                                <div class="u_e_img">
                                    <img v-if="user.avatar_url" :src="user.avatar_url" alt="">
                                    <img v-else src="/images/user-img.jpg" alt="">
                                </div>
                                <div class="user_edit_btn">
                                    <button type="button">Change Image</button>
                                </div>    
                                </div>
                        </div>   
                        <div class="col-md-12">
                            <div class="model_btn">
                                <button type="submit" class="save_profile_btn">Submit</button>
                            </div>
                        </div>
                    </div>
                </div>
            </form>

        </modal>
    </div>
</template>
<script>
    import RadialProgressBar from 'vue-radial-progress'
    export default {
        props: ['user'],
        data() {
            return {
                interests: [],
                interest_enable: true,
                profile_data: {
                    profile_pic: '',
                    email: '',
                    fb_url: '',
                    insta_url: '',
                    linked_url: '',
                }
            };

        },
        components: {
            RadialProgressBar
        },
        watch: {
            user(val) {
                this.setProfile(val);
            }
        },
        mounted() {
            this.axios.get('/api/get-interests').then((resp) => {
                // this.interest_enable=resp.data.success.interest_enable;
                this.interests = resp.data.success.interests;
            })
        },
        methods: {
             addDoubtModal(){
            this.$modal.show('add_doubt_modal');
        },
            saveProfile() {
                this.axios.post('/api/save-profile', {
                    data: this.profile_data
                }).then((resp) => {
                    this.setProfile(resp.data.success.profile);
                });
            },
            setProfile(profile) {
                this.profile_data.email = profile.email;
                this.profile_data.profile_pic = profile.avatar_url;
                this.profile_data.fb_url = profile.fb_url;
                this.profile_data.insta_url = profile.insta_url;
                this.profile_data.linked_url = profile.linked_url;
            }
        }


    }

</script>
<style>
.progess_bar {
    display: flex;
    flex-wrap: wrap;
    justify-content: space-around;
}
.progess_bar circle {
    stroke-width: 8px !important;
}
.user_interest h4 {
    color: #868686;
}
h3.user_profile_name span {
    font-size: 14px;
    color: #868686;
    cursor: pointer;
}

h3.user_profile_name {
    display: flex;
    justify-content: space-between;
    align-items: center;
}
button.save_profile_btn {
    border: navajowhite;
    background-color: blue;
    color: white;
    padding: 10px 40px;
    border-radius: 5px;
    margin-top: 10px;
    margin-bottom: 10px;
    font-weight: 500;
    font-size: 16px;
}
.user_int_text p {
    color: #868686;
    margin-bottom: 25px;
}
.user_interest {
    margin-top: 50px;
}
.cojl p {
    margin-bottom: 0;
}
.u_e_img img {
    width: 80px;
    height: 80px;
    border-radius: 50px;
}
.user_edit_profile_img {
    display: flex;
    align-items: center;
}
.user_edit_btn button {
    background-color: blue;
    border: none;
    color: white;
    padding: 5px 8px;
    font-size: 13px;
    border-radius: 5px;
}

.user_edit_btn {
    margin-left: 20px;
}
</style>
