<template>
    <div>
        <div class="container pt-100">
            <div class="user_profile_page">
                <div class="row">
                    <div class="col-md-8 center-col">
            <div class="row">
                <div class="col-md-3">
                    <div class="user_profile_img">
                        <img src="/images/user-img.jpg" alt="">
                    </div>   
                </div>
                <div class="col-md-9">
                    <div class="user_des">
                        <h3 class="user_name"> Robert Downey Jr.</h3>
                        <p>This data is generated by your interaction with posts,hence the more you interect with posts the more
                             precise this data is. Currently we don't have enough data to analys your interest.
        Please share at least 3 Posts to generate this data.</p>
                    </div>
                    <div class="user_social_links">
                        <div class="user_social_link_left">
                            <span><i class="fab fa-facebook-f"></i></span>
                            <span><i class="fab fa-linkedin"></i></span>
                            <span><i class="fab fa-instagram"></i></span>
                            <span><i class="fab fa-twitter"></i></span>
                            
                        </div>
                          <div class="user_friend_left">
                             <h5>Your Friends <span>25</span></h5> 
                          </div>       
                    </div>      
                </div>      
            </div>  
                    </div>
                </div> 
    <div class="user_interest">
        <h4>Your Interest</h4>
        <div class="row">
            <div class="col-md-12">
        <radial-progress-bar :diameter="200"
                       :completed-steps="completedSteps"
                       :total-steps="totalSteps">
   <p>Total steps: {{ totalSteps }}</p>
   <p>Completed steps: {{ completedSteps }}</p>
  </radial-progress-bar>
            </div>
        </div>
    </div>

          <!-- <img :src="user.avatar_url">
        <p>{{user.full_name}}</p>
        This data is generated by your interaction with posts,
        hence the more you interect with posts the more precise this data is. 
        
        <div v-if="interests.length===0">
        Currently we don't have enough data to analys your interest.
        Please share at least 3 Posts to generate this data.
        </div>
        <div v-for="interest in interests" :key="interest.id">{{interest.category_name}}{{interest.percent}}</div> -->
    </div>

    </div>
    </div>
</template>
<script>
import RadialProgressBar from 'vue-radial-progress'
export default {
    props:['user'],
    data(){
        return {
            interests:[],
            interest_enable:true,
            completedSteps: 0,
      totalSteps: 9
        };
        
    },
     components: {
    RadialProgressBar
  },
    mounted(){
        this.axios('/api/get-interests').then((resp)=>{
            // this.interest_enable=resp.data.success.interest_enable;
            this.interests=resp.data.success.interests;
        })
    }
    
    
}
</script>
<style >

</style>