<?php

use Illuminate\Database\Seeder;

class BranchesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $sql = "INSERT INTO `branches` (`branch_name`) VALUES
        ('Astronomy, Astrophysics and Space Engineering'),
('Economics, Psychology, English, Philosophy, Sociology, History'),
('Electrical Engineering with specialisation in Communication and Signal Processing'),
('Electrical Engineering with specialisation in VLSI Design and Nanoelectronics'),
('Mechanical Engineering (Design)'),
('Access to Justice'),
('Accounting and Finance'),
('Actuarial Science'),
('Advanced Manufacturing and Design'),
('Advertising and Marketing Management'),
('Aeronautical Engineering'),
('Aerospace Engineering'),
('Agri Business'),
('Agricultural Economics'),
('Agricultural Engineering'),
('Agricultural Extension and Communication'),
('Agricultural Meteorology'),
('Agricultural Microbiology'),
('Agriculture'),
('Agriculture and Food Business'),
('Agriculture and Food Business'),
('Agriculture Engineering'),
('Agroforestry'),
('Agronomy'),
('Airport and Aviation Business Management'),
('Alternate Hydro Energy Systems'),
('Alternative Dispute Resolution'),
('Analytical Chemistry'),
('Anasthesia Techology'),
('Anatomy'),
('Ancient Indian History, Culture and Archealogy'),
('Animal Biology and Biotechnology'),
('Animation'),
('Animation and Graphic Design'),
('Animation with International Moving Image Society, UK (Chartered Body)'),
('Anthropology'),
('Applicable Mathematics'),
('Applied Chemistry'),
('Applied Chemistry and Polymer Technology'),
('Applied Electronics'),
('Applied Geochemistry'),
('Applied Geology'),
('Applied Linguistics'),
('Applied Mathematics'),
('Applied Microbiology'),
('Applied Philosophy'),
('Applied Physics'),
('Applied Psychology'),
('Applied Psychology (Clinical Psychology)'),
('Applied Psychology (Counseling Psychology)'),
('Applied Science and Engineering'),
('Applied Statistics'),
('Apprel and Textile Science'),
('Aquaculture'),
('Arabic'),
('Architectural Design'),
('Architecture'),
('Architecture and Planning'),
('Architecture and Regional Planning'),
('Artificial Intelligence'),
('Arts'),
('Astronomy'),
('Atmosphere and Ocean Sciences'),
('Audiology'),
('AUDIOLOGY AND SPEECH LANGUAGE PATHOLOGY (BASLP)'),
('Automobile Engineering'),
('Automotive Electronics'),
('Automotive Engineering'),
('Automotive Technology'),
('Autonomous Unmanned Vehicle Technologies'),
('Aviation Management'),
('Avionics'),
('B. Design - (Product design / Interior design)'),
('Bachelor of Arts and Bachelor of Laws'),
('Bachelor of Arts and Bachelor of Laws Honors'),
('Bachelor of Business Administration and Bachelor of Laws'),
('Bachelor of Business Administration and Bachelor of Laws Honors'),
('Banking and Finance'),
('Banking and Insurance'),
('Basic Sciences'),
('Bengali'),
('Bharathanatyam '),
('Big Data Analytics'),
('Bio Science'),
('Bio Technology'),
('Bio-Informatics'),
('Bio-Medical Engineering'),
('Biochemical'),
('Biochemical Engineering'),
('Biochemistry'),
('Bioinformatics'),
('Biological Sciences'),
('Biomedical Engineering (BME)'),
('Biomedical Genetics'),
('Biomedical Instrumentation'),
('Biomedical Signal Processing and Instrumentation'),
('Bioprocess Engineering'),
('Bioprocess Technology'),
('BioScience and Bio Engineering'),
('Biosciences and Biomedical Engineering'),
('Biostatistics'),
('Biotechnology'),
('Biotechnology (spec. in Genetic Engineering )'),
('Biotechnology (spec. in Regenerative Medicine )'),
('Biotechnology and Biochemical Engineering'),
('Biotechnology with Artificial Intelligence and Machine Learning'),
('Botany'),
('Business Administration'),
('Business Analytics'),
('Business Development'),
('Business Management'),
('Business Process Services (BPS)'),
('Business Studies'),
('CA'),
('CAD'),
('CAD / CAM'),
('CAD, CAM and Robotics'),
('Cardiac Care Technology'),
('Cardiac Perfusion Technology (CPT)'),
('Cardiovascular Technology'),
('Career Guidance'),
('Career Guidance and Councelling'),
('Catering Science and Hotel Management'),
('Centre for Oceans, Rivers, Atmosphere and Land Sciences Earth System Science and Technology'),
('Centre for Transportation (CTRANS)'),
('Ceramic'),
('Chemical and Biochemical Engineering'),
('Chemical Engineering'),
('Chemical Sciences'),
('Cheminformatics'),
('Chemistry'),
('Children and Families'),
('Cinema and Television'),
('Civil'),
('Civil and Environmental Engineering'),
('Civil Engineering'),
('Civil Engineering (Infrastructure Engineering and Management)'),
('Civil Engineering and Structural Engineering'),
('Civil Engineering and Transportation Engineering'),
('Civil Engineering Construction Engineering and Management'),
('Civil Engineering Environmental Engineering and Management'),
('Civil Engineering Geotechnical Engineering'),
('Civil Engineering Hydraulic and Water Resources Engineering'),
('Civil with Artificial Intelligence and Machine Learning'),
('Climate Change and Sustainability Studies'),
('Climate Sciences'),
('Climate Studies'),
('Clinical Embryology'),
('Clinical Research'),
('Cloud and Information Security integrated with KPMG Certified Cyber Security Professional'),
('Cloud Computing'),
('Cognitive Sciences'),
('Commerce'),
('Commerce and Management'),
('Commercial Photography'),
('Commercial Photography and Cinematography'),
('Communication'),
('Communication and Journalism'),
('Communication and Signal Processing (EE)'),
('Communication Engineering'),
('Communication System Engineering'),
('Community Development'),
('Community Science (Honors)'),
('Comparative Literature'),
('Computational Design'),
('Computational Engineering and Networking'),
('Computational Neuroscience'),
('Computer'),
('Computer Aided Structural Analysis and Design'),
('Computer and Communication Engineering'),
('Computer Applications'),
('Computer Engineering'),
('Computer Engineering (Cloud Technology and Mobile Application)'),
('Computer Integrated Design and Manufacturing'),
('Computer Science'),
('Computer Science and Engineering with a Specialization in Blockchain Technology'),
('Computer Science and Engineering with specialization in Cyber Physical Systems'),
('Computer Science (Data Science)'),
('Computer Science and Business System'),
('Computer Science and Engineering'),
('Computer Science and Engineering (Spec. in Artificial Intelligence and Machine Learning)'),
('Computer Science and Engineering (Spec. in Big Data Analytics)'),
('Computer Science and Engineering (Spec. in Bioinformatics)'),
('Computer Science and Engineering (Spec. in Cyber Security)'),
('Computer Science and Engineering (Spec. in Data Analytics)'),
('Computer Science and Engineering (Spec. in Information Security)'),
('Computer Science and Engineering (Spec. in Information Technology and Entrepreneurship)'),
('Computer Science and Engineering (Spec. in Information Technology)'),
('Computer Science and Engineering (Spec. in Internet of Things (IOT))'),
('Computer Science and IT'),
('Computer Science and Technology'),
('Computer Technology'),
('Computing and Electrical Engineering'),
('Constitutional Law'),
('Construction Technology and Management'),
('Control and Automation'),
('Control and Instrumentation'),
('Control Systems'),
('Corporate Accounting with CMA USA integration'),
('Corporate Finance Integrated with CPA, USA + EA, USA'),
('Corporate Law'),
('Corporate Secretaryship'),
('Costume Design and Fashion'),
('Counselling'),
('Criminology and Justice'),
('Cryogenic Engineering'),
('Culinary Arts'),
('Cyber Forensics and Information Security'),
('Cyber Physical Systems'),
('Cyber Security'),
('Cyber Security and Cyber Law'),
('Cyber Security Systems and Networks'),
('Dalit and Tribal Studies and Action'),
('Dance'),
('Data Analytics'),
('Data and Computational Science'),
('Data Science'),
('Data Science and Business Analytics'),
('Data Sciences and Data Analytics'),
('Database Systems'),
('Deglutology and Swallowing Disorders'),
('Dental Mechatronics'),
('Design'),
('Design and Manufacturing'),
('Design Engineering'),
('Development Policy, Planning and Practice'),
('Development Studies'),
('Diabetes Sciences (DBS)'),
('Dialysis Technology'),
('Dialysis Therapy (DIT)'),
('Digital and Cyber Forensic'),
('Digital Animation'),
('Digital Humanities'),
('Digital System'),
('Digital Systems and Signal Processing'),
('Diploma of Pharmacy'),
('Disability Studies and Action'),
('Disaster Management'),
('Disaster Mitigation and Management'),
('Disaster Mitigation and Management'),
('Drug Regulatory Affairs'),
('Dyestuff Technology'),
('E-Commerce'),
('E-Learning Technology'),
('Earth Sciences'),
('Earthquake Engineering'),
('ECE with Internet of Things (IoT)'),
('Echocardiography Technology (ECT)'),
('Ecocardiography'),
('Ecology, Environment and Sustainable Development'),
('Econometrics'),
('Economics'),
('Economics, Statistics, Mathematics'),
('Ecosophical Aesthetics'),
('Education'),
('Education (Elementary)'),
('Education Studies'),
('EEE with Robotics and Automation'),
('Electric Drives and Power Electronics'),
('Electrical and Electronics Engineering'),
('Electrical Engineering'),
('Electrical Engineering (Instrumentation Engineering)'),
('Electrical Engineering (Power System)'),
('Electrical Engineering (Spec. in VLSI)'),
('Electrical Engineering and Power Electronics and Drives'),
('Electrical Engineering Control System Engineering'),
('Electrical Engineering Instrumentation and Signal Processing'),
('Electrical Engineering with specialisation in Signal Processing and Communication'),
('Electronics'),
('Electronics and Computer Engineering'),
('Electronics - VLSI Design'),
('Electronics and Communication'),
('Electronics and Communication Engineering'),
('Electronics and Communication Engineering (Spec. in Communication System)'),
('Electronics and Communication Engineering (Spec. in Medical Electronics)'),
('Electronics and Communication Engineering (spl. In Biomedical Engineering)'),
('Electronics and Communication Engineering (spl. In Micro Electronic Systems and Embedded Technology)'),
('Electronics and Communication Engineering with Artificial Intelligence and Machine Learning'),
('Electronics and communication systems'),
('Electronics and Communication with (spl. In VLSI)'),
('Electronics and Control Engineering'),
('Electronics and Design'),
('Electronics and Electrical Communication Engineering Microelectronics and VLSI Design'),
('Electronics and Electrical Communication Engineering RF and Microwave Engineering'),
('Electronics and Electrical Engineering'),
('Electronics and Instrumentation'),
('Electronics and Instrumentation Engineering'),
('Electronics and Telecommunication'),
('Electronics and Telecommunication Engineering'),
('Electronics Design and Technology'),
('Electronics Engineering'),
('Electronics Science'),
('Embedded Control System'),
('Embedded System and Technologies'),
('Embedded Systems Engineering'),
('Emergency Medical Tech'),
('Emergency Medicine'),
('Emerging Technologies'),
('Emerging Technologies in Management'),
('Energy and Environmental Engineering'),
('Energy and Infrastructure Management'),
('Energy Engineering'),
('Energy Engineering (Spec. in Materials)'),
('Energy Science and Engineering'),
('Energy Studies'),
('Energy Systems (Focused on Solar Energy)'),
('Engineering'),
('Engineering Design'),
('Engineering Physics'),
('Engineering Science'),
('English'),
('English and Languages'),
('English Language Studies'),
('Entomology'),
('Entrepreneurship'),
('Entrepreneurship and International Trade'),
('Entrepreneurship and Family Business'),
('Environment and Occupational Health'),
('Environment and Water Resource Engineering'),
('Environment Science'),
('Environmental chemistry'),
('Environmental Engineering'),
('Environmental Management'),
('Environmental Management of Rivers and Lakes'),
('Environmental Science'),
('Environmental Science and Engineering'),
('Environmental Sciences'),
('Environmental Studies'),
('Epidemology'),
('European Studies'),
('Exercise and Sports Sciences'),
('Extension Education'),
('Extension Education and Communication Management'),
('Family Business and Entrepreneurship'),
('Family Resource Management'),
('Farm Machinery and Power Engineering'),
('Fashion Design'),
('Fashion Retail Management'),
('Fashion Technology'),
('Fibres and Textile Processing Technology'),
('Film and Television Production'),
('Film and TV Production'),
('Finance'),
('Finance and Accounting'),
('Finance and Computer Applications'),
('Finance and HR'),
('Financial Analysis with KPMG International Accounting Practices'),
('Financial Economics'),
('Financial Investment Analysis'),
('Financial Management'),
('Financial Markets'),
('Financial Technology'),
('Fine Arts'),
('Flim Technology'),
('Floriculture and Landscape Architecture'),
('Floriculture and Landscaping'),
('Food and Nutrition'),
('Food and Nutritional Biotechnology'),
('Food Biotechnology'),
('Food Engineering and Technology'),
('Food Processing Technology'),
('Food Safety and Quality Management'),
('Food Science and Nutrition'),
('Food Science and Technology'),
('Food Science Technology'),
('Food Technology'),
('Food Technology'),
('Food, Nutrition and Dietetics'),
('Food, Nutrition and Dietetics'),
('Foreign Languages and Intercultural Studies'),
('Forensic Odontology'),
('Forensic Science'),
('Forensic Sciences'),
('Forest Genetic Resources'),
('Forestry'),
('French'),
('Fruit Science'),
('General'),
('General Management'),
('Genetic Engineering'),
('Genetics'),
('Genetics and Plant Breeding'),
('Geo Informatics and Remote Sensing'),
('Geo-exploration and Petroleum Geo-sciences'),
('Geo-informatics'),
('Geo-Technical and Geo-Environmental Engineering'),
('Geography'),
('Geology'),
('Geology and Geophysics'),
('Geomatics Engineering '),
('Geophysics'),
('Geotechical Engineering'),
('German'),
('Global Accounting Practices with Association of International Accounts'),
('Global Health'),
('Global Logistics and Supply Chain Management'),
('Global Management Accountant Integrated with CIMA, UK + IMA, USA + CMA Australia'),
('Global studies'),
('Globalisation and Labour'),
('Governance and Public Administration'),
('Graphic Design'),
('Graphics and mutlimedia'),
('Green Technology'),
('Ground Water Hydrology'),
('Guidance and Counselling'),
('Health Administration'),
('Health Care Quality and  Safety'),
('Health Economics'),
('Health Economics and  Outcomes Research'),
('Health Policy, Economics and Finance'),
('Heat and Power'),
('Herbal technology'),
('Hindi'),
('History'),
('History and Tourism'),
('Home Science - Clinical Nutrition and Dietetics'),
('Home Science - Nutrition Food Service Management and Dietetics'),
('Horticulture'),
('Hospital and Health System Management'),
('Hospital Administration'),
('Hospital and Health Care Management'),
('Hospital Management'),
('Hospitality and Hotel Administration (H. and H.A.)'),
('Hospitality Management'),
('Hotel Management'),
('Hotel Management and Catering Technology (BHM and CT)'),
('Human Development and Family Studies'),
('Human Genetics'),
('Human Genetics and Molecular Biology'),
('Human Physiology'),
('Human Resource Management'),
('Human resource Management and Industrial Relations'),
('Human Resource Management and Labour Relations'),
('Humanities'),
('Humanities and Social Sciences'),
('Hydraulic Engineering'),
('Hydraulics and Water Resource Engineering'),
('Hydro and Renewable Energy'),
('Hydrogeology'),
('Hydrology'),
('I C Technology'),
('Immunology'),
('Inductrial Biotechnology'),
('Industrial and Production'),
('Industrial Biotechnology'),
('Industrial Engineering'),
('Industrial Engineering and Operation Research'),
('Industrial Engineering and Management'),
('Industrial Metallurgy'),
('Industrial Microbiology'),
('Industrial Pharmacy'),
('Industrial Safety Engineering'),
('Information and Communication Technology'),
('Information and Cyber security'),
('Information Science and Engineering'),
('Information Security'),
('Information Security integrated with KPMG Advanced Certified Cyber Security Professional**'),
('Information System (IS)'),
('Information Technology'),
('Infrastructure Engineering and Management'),
('Infrastructure Systems'),
('Innovation and Entrepreneurship'),
('Inorganic Chemistry'),
('Institute Instrumentation Centre '),
('Instrumentation and Control Engineering'),
('Insurance and Banking Management'),
('Insurance, Banking and Finance'),
('Integrated M. Phil.-Ph. D. Programme in Education'),
('Integrated M. Phil.-Ph. D. Programme in Social Sciences'),
('Integrated M.Phil Ph.D. in Social Sciences with Specialisation in Sociology of Education'),
('Integrated M.Phil-Ph.D programme School of Habitat Studies'),
('Integrated M.Phil.-Ph.D. in Inclusive Development and Social Justice'),
('Integrated M.Phil.-Ph.D. Programme in Development Studies'),
('Integrated M.Phil.-Ph.D. Programme in Management and Labour Studies'),
('Integrated M.Phil.-Ph.D. Programme in Public Health'),
('Integrated M.Phil.-Ph.D. Programme in Rural Development'),
('Integrated M.Phil.-Ph.D. Programme in Social Work'),
('Integrated M.Phil.-Ph.D. Programme in Women's Studies'),
('Integrated Power System'),
('Intellectual Property Rights'),
('Intellectual Property Rights and Cyber Law'),
('Intensive Care Technology'),
('Interdisciplinary Studies'),
('Interior Design'),
('Interior Design (Honors) with Chartered Institute of Architectural Technologists, UK'),
('Interior Design with Chartered Society of Designers, UK'),
('International Accounting and Finance with ACCA UK integration#'),
('International Banking and Finance'),
('International Business'),
('International Business integrated with Chartered Institute of Marketing, UK'),
('International Law'),
('International Marketing integrated with Digital Marketing Institute, Ireland'),
('International Relations'),
('International Trade and Economic Law'),
('IOT and Applications'),
('IOT integrated with Foundation Certification in Cloud Technology from Micro Focus (Formerly HPE)'),
('Irrigation Water Management'),
('Islamic Studies'),
('IT Business Management'),
('Journalism'),
('Journalism and Communication'),
('Journalism and Mass Communication'),
('Labour Law'),
('Labour Studies and Social Protection'),
('Law'),
('Liberal Arts'),
('Library and Information Science'),
('Life Sciences'),
('Linguistics'),
('Livelihoods and Social Entrepreneurship'),
('Logistics'),
('Logistics and Supply Chain Management'),
('LSCM+Chartered Institute of Procurement and Supply (CIPS)-UK'),
('M.Arch'),
('Machine Design'),
('Management'),
('Management Accounting'),
('Management Sciences'),
('Management Studies'),
('Manufacturing and Automation'),
('Manufacturing Engineering'),
('Manufacturing Technology'),
('Manufacturing Technology and Automation'),
('Marine Engineering'),
('Marketing'),
('Marketing and Finance'),
('Marketing and HR'),
('Marketing and Sales'),
('Mass Communication'),
('Master of Business Administration'),
('Material Science and Technology'),
('Material Science Engineering (MEMS)'),
('Materials Engineering'),
('Materials Science and Engineering'),
('Materials Science and Metallurgical Engineering'),
('Maternal and Child Health'),
('Mathematical Sciences'),
('Mathematics'),
('Mathematics and Applied Statistics and Informatics'),
('Mathematics and Statistics'),
('Mathematics and Computing'),
('Maths with Computer Application'),
('Mechanical'),
('Mechanical and Industrial Engineering'),
('Mechanical Engineering'),
('Mechanical Engineering (Spec. Artificial Intelligence and Machine Learning)'),
('Mechanical Engineering (Spec. Computer Aided Engineering)'),
('Mechanical Engineering (spec. in Automotive Engineering)'),
('Mechanical Engineering (Spec. in Electric and Hybrid Vehicles)'),
('Mechanical Engineering (Spec. in Energy Systems)'),
('Mechanical Engineering (Spec. in Smart Manufacturing)'),
('Mechanical Engineering (Thermal)'),
('Mechanical Engineering - CAD/CAM'),
('Mechanical Engineering and Manufacturing Engineering'),
('Mechanical Engineering and Mechanical System Design'),
('Mechanical Engineering and Thermal Science and Engineering'),
('Mechanical Engineering Manufacturing Sc. and Engg.'),
('Mechanical Engineering Mechanical systems Design'),
('Mechanical Engineering with specialisation in Production and  Industrial Engineering'),
('Mechanical System Design(ME)'),
('Mechanical with specialization in Cyber Physical Systems '),
('Mechatronics'),
('Mechatronics and Automation '),
('Mechatronics Engineering'),
('Media and Communications'),
('Media and Cultural Studies'),
('Media Studies'),
('Media Technology'),
('Medical and Psychiatric Social work'),
('Medical Anatomy'),
('Medical Biochemistry'),
('Medical Biotechnology'),
('Medical Electronics'),
('Medical Imaging Technology'),
('Medical Lab Technology'),
('Medical Laboratory Technology (MLT)'),
('Medical Microbiology'),
('Medical Pharmacology'),
('Medical Physics'),
('Medical Physiology'),
('Medical Statistics'),
('Medical Technology'),
('Medicinal and Aromatic Plants'),
('Mental Health'),
('Metallurgical and Material Science Engineering'),
('Metallurgical and Materials'),
('Metallurgical and Materials Engineering'),
('Metallurgical and Materials Engineering Metal. and Materials Engineering'),
('Metallurgy and Material Science Engineering'),
('Metallurgy Engineering  and Materials Science'),
('Metallurgy Engineering and Materials Science with specalisation in Metallurgy Engineering'),
('Metallurgy Engineering and Materials Science with specialisation in Material Science and Engineering'),
('Microbiology'),
('Microwave and Optical Communication'),
('Mining Engineering'),
('Mobile Applications and Cloud Technology integrated with Foundation Certification in Mobile Application from Micro Focus (Formerly HPE) **'),
('Molecular Biology'),
('Molecular Biology and biotechnology'),
('Molecular Microbiology'),
('Molecular Plant Breeding'),
('Multimedia'),
('Multimedia and Animation'),
('Multimedia and Communication'),
('MURP'),
('Music'),
('NA'),
('Nano Science and Technology'),
('Nano Sciences'),
('Nano Technology'),
('Nanotechnology'),
('Natural Resource and Governance'),
('Nematology'),
('Network Engineering'),
('Neural and Cognitive Science'),
('Neuro Electro Physiology (NEP)'),
('Neuro-Science Technology'),
('Non- Medical'),
('Nuclear Science and Technology'),
('Nursing'),
('Nutrition'),
('Nutrition and Dietetics'),
('Occupational Therapy'),
('Ocean Engineering and Naval Architecture'),
('Ocean Engineering and Naval Architecutre Ocean Engg. and Naval Arch.'),
('Oils, Oleochemicals and Surfactants Technology'),
('Operation and Anaesthesia Technology'),
('Operations and Systems'),
('Operations Management'),
('Optometry'),
('Optometry (OPT)'),
('Organic Chemistry'),
('Organisation Development, Change and Leadership'),
('Packaging Technology'),
('Painting, Print Making, Sculpture'),
('Patient Care Management'),
('Peace and Conflict Studies'),
('Performing Arts'),
('Perfumery and Flavour Technology'),
('Perfusion Technology'),
('Persian'),
('Petroleum Engineering'),
('Petroleum Technology'),
('Pharmaceutical'),
('Pharmaceutical Analysis'),
('Pharmaceutical Bio-Technology'),
('Pharmaceutical Chemistry'),
('Pharmaceutical Science and Technology'),
('Pharmaceutical Technology'),
('Pharmaceutics'),
('Pharmacognosy'),
('Pharmacognosy and Phytochemistry'),
('Pharmacology'),
('Pharmacy'),
('Pharmacy Administration'),
('Pharmacy Practice'),
('Pharmcology'),
('Philosophy'),
('Photography'),
('Photography and Cinematography'),
('Photonics'),
('Physical Chemistry'),
('Physical Education'),
('Physical Sciences'),
('Physician Assistant (PA)'),
('Physics'),
('Physics Functional Materials and Devices'),
('Physiology'),
('Physiotherapy'),
('Planning'),
('Plant Biology and Biotechnology'),
('Plant Biology and Plant Technology'),
('Plant Breeding and Genetics'),
('Plant Nematology'),
('Plant Pathology'),
('Plant Physiology'),
('Plant Sciences'),
('Plant Tissue Culture'),
('Plastic Engineering'),
('Policy Studies'),
('Political Science'),
('Political Science - International Relations'),
('Polymer and Chemical technology'),
('Polymer and Process Engineering'),
('Polymer Engineering and Technology'),
('Polymer Science and Chemical Technology'),
('Population Studies'),
('Power and Energy Systems'),
('Power Electronics'),
('Power Electronics and Drives'),
('Power Electronics and Machine Drives'),
('Power Electronics and Power System'),
('Power System Engineerig'),
('Power System Engineering'),
('Power Systems and Automation'),
('PR and Event Management'),
('Print and Media Technology'),
('Printing Technology'),
('Process Instrumentation'),
('Process Metallurgy'),
('Processing and Food Engineering'),
('Production and Industrial Engineering'),
('Production and Industrial Engineering (ME)'),
('Production Engineering'),
('Production Engineering And Industrial Management'),
('Professional Accounting (PA)'),
('Project Management'),
('Psychiatric Social Work'),
('Psychology'),
('Public Administration'),
('Public Health'),
('Public Policy and Governance'),
('Pulp and Paper'),
('Pulp and Paper Engineering'),
('Quality and Reliability'),
('Quality Assurance'),
('Quality Assurance Techniques'),
('Quantum Information and Computation'),
('Radiology'),
('Regulatory Affairs'),
('Regulatory Governance'),
('Remote Sensing and Wireless Sensor Networks'),
('Remote Sensing and Geographic Information Systems'),
('Renal Dialysis Technology'),
('Renal Replacement Therapy and Dialysis Technology'),
('Renewable Energy Engineering'),
('Resources Engineering'),
('Respiratory Care Technology'),
('Respiratory Therapy'),
('Respiratory Therapy (RPT)'),
('Retail Management'),
('RF and MW'),
('Risk Management with CIMA UK integration #'),
('Robotics'),
('Robotics and Automation'),
('Rural Development'),
('Rural Management'),
('Sales and Marketing'),
('Sanskrit'),
('Science'),
('Sciences'),
('Seed Science and Technology'),
('Seismic Vulnerability and Risk Assessment'),
('Sensor System Technology'),
('Sensors and Internet of Things'),
('Sericulture'),
('Signal Processing'),
('Signal Processing and Digital Design'),
('Silviculture'),
('Smart Healthcare'),
('Smart Manufacturing'),
('Social Entrepreneurship'),
('Social Exclusive and Inclusive Policy'),
('Social Innovation and Entrepreneurship'),
('Social Science'),
('Social Work'),
('Society and Culture'),
('Sociology'),
('Sociology and Social Anthropology'),
('Software Application Development, Software Testing'),
('Software Engineering'),
('Software Technology'),
('Soil and Water Engineering'),
('Soil Dynamics'),
('Soil Science'),
('Soil Science and Agricultural Chemistry'),
('Solar and Alternative Energy'),
('Solid State Electronic Materials'),
('South East Asian Studies'),
('Southeast Asian and Pacific Studies'),
('Space Technologies'),
('Spanish'),
('Special Education'),
('Speech Language Pathology'),
('Spices, Plantation, Medicinal and Aromatic Plants'),
('Sports Physiotherapy'),
('Statistics'),
('Statistics with Computer Applications'),
('Storage and Cloud Technology integrated with Advanced Certification in Cloud Technology from Micro Focus (Formerly HPE) **'),
('Structural and Construction Engineering'),
('Structural Dynamics'),
('Structural Engineering'),
('Structural Engineering and Disaster Management'),
('Surface Engineering and Technology'),
('Surface Water Hydrology'),
('Sustainable Architecture'),
('Sustainable Livelihoods and Natural Resources Governance'),
('Systems and Control Engineering'),
('Tamil'),
('Technology Alternatives'),
('Telecom Management'),
('TELECOMMUNICATION ENGINEERING'),
('Telugu'),
('Textile Chemistry'),
('Textile Design'),
('Textile Engineering'),
('Textile Engineering and Management'),
('Textile Technology'),
('Textiles and Apparel Design'),
('Theatre Arts'),
('Thermal and Fluid Science'),
('Thermal Engineering'),
('Thermal Power Engineering'),
('Thermal Science'),
('Thermofluids Engineering'),
('Three Subject Combination'),
('Tourism Administration'),
('Tourism and Hospitality Management'),
('Tourism and Hospitality Management integrated with Chartered Institute of Hospitality, UK'),
('Town and Country planning'),
('Translation Studies'),
('Transportation and Infrastructure Engineering'),
('Transportation Systems Engg'),
('Travel and Tourism'),
('Travel and Tourism Management'),
('Tribology and Maintenance'),
('Urban Design'),
('Urban Policy and governance'),
('Urban Science and Engineering'),
('Urdu'),
('Vegetable Science'),
('Virology'),
('Visual Arts'),
('Visual Communication'),
('Visual Media and Communication'),
('VLSI'),
('VLSI and Embedded Systems'),
('VLSI Design'),
('VLSI Design and Embedded system'),
('Water Policy and Governance'),
('Water Resources Development'),
('Water Resources Development and Management - Irrigation Water Management'),
('Water Resources Development and Management - Water Resource Management'),
('Water Resources Engineering'),
('Water Resources Engineering and Management'),
('Watershed Management'),
('Web Applications'),
('Welding Engineering'),
('Wired and Wireless Communication'),
('Wireless Networks and Applications'),
('Women-Centred Practice'),
('Womens Studies'),
('Wood Science and Technology'),
('Yoga Therapy'),
('Zoology')";
        DB::unprepared($sql);
    }
    }
