<?php

use Illuminate\Database\Seeder;

class CoursesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        $sql = "INSERT INTO `courses` (`id`, `course_name`, `course_level`, `country_id`) VALUES
(1, 'Bachelor of Arts (B.A)', 'Under Graduation', 'IN'),
(2, 'Bachelor of Arts Bachelor of Education (B.A. B.Ed)', 'Under Graduation', 'IN'),
(3, 'Bachelor of Arts Bachelor of Law (B.A.B.L)', 'Under Graduation', 'IN'),
(4, 'Bachelor of Arts Bachelor of Law (B.A.LLB)', 'Under Graduation', 'IN'),
(5, 'Bachelor of Ayurvedic Medicine and Surgery (B.A.M.S)', 'Under Graduation', 'IN'),
(6, 'Bachelor of Applied Sciences (B.A.S)', 'Under Graduation', 'IN'),
(7, 'Bachelor of Arts (B.A.S.L.P)', 'Under Graduation', 'IN'),
(8, 'Bachelor of Audiology and Speech Language Pathology (B.A.S.L.P)', 'Under Graduation', 'IN'),
(9, 'Bachelor of Architecture (B.Arch)', 'Under Graduation', 'IN'),
(10, 'Bachelor of Business Administration (B.B.A)', 'Under Graduation', 'IN'),
(11, 'Bachelor of Business Administration Bachelor of Law (B.B.A LL.B)', 'Under Graduation', 'IN'),
(12, 'Bachelor of Business Management (B.B.M)', 'Under Graduation', 'IN'),
(13, 'Bachelor of Business Studies (B.B.S)', 'Under Graduation', 'IN'),
(14, 'Bachelor of Computer Applications (B.C.A)', 'Under Graduation', 'IN'),
(15, 'Bachelor of Communication Journalism (B.C.J)', 'Under Graduation', 'IN'),
(16, 'Bachelor of Computer Science (B.C.S)', 'Under Graduation', 'IN'),
(17, 'Bachelor of Commerce (B.Com)', 'Under Graduation', 'IN'),
(18, 'Bachelor of Divinity (B.D)', 'Under Graduation', 'IN'),
(19, 'Bachelor of Dental Surgery (B.D.S)', 'Under Graduation', 'IN'),
(20, 'Basic Development Therapy (B.D.T)', 'Under Graduation', 'IN'),
(21, 'Bachelor of Design (B.Des)', 'Under Graduation', 'IN'),
(22, 'Bachelor of Engineering (B.E)', 'Under Graduation', 'IN'),
(23, 'Bachelor of Electronic Science (B.E.S)', 'Under Graduation', 'IN'),
(24, 'Bachelor of Education (B.Ed)', 'Under Graduation', 'IN'),
(25, 'Bachelor of education in Artificial Intelligence (B.Ed AI)', 'Under Graduation', 'IN'),
(26, 'Bachelor of Education (B.EdQ)', 'Under Graduation', 'IN'),
(27, 'Bachelor of Elementary Education (B.EI.ED)', 'Under Graduation', 'IN'),
(28, 'Bachelor of Elementary Education (B.EL.Ed)', 'Under Graduation', 'IN'),
(29, 'Bachelor of Fine Arts (B.F.A)', 'Under Graduation', 'IN'),
(30, 'Bachelor of Financial Investment and Analysis (B.F.I.A)', 'Under Graduation', 'IN'),
(31, 'Bachelor of Fishery Sciences (B.F.S)', 'Under Graduation', 'IN'),
(32, 'Bachelor of Fashion Technology (B.F.Tech)', 'Under Graduation', 'IN'),
(33, 'Bachelor of General Law (B.G.L)', 'Under Graduation', 'IN'),
(34, 'Behavioral Healthcare Education (B.H.Ed)', 'Under Graduation', 'IN'),
(35, 'Bachelor of Hotel Management (B.H.M)', 'Under Graduation', 'IN'),
(36, 'Bachelor Hotel Management and Catering Technology (B.H.M.C.T)', 'Under Graduation', 'IN'),
(37, 'Bachelor of Homeopathic Medicine & Surgery (B.H.M.S)', 'Under Graduation', 'IN'),
(38, 'Bachelor of Hospitality and Tourism Management (B.H.T.M)', 'Under Graduation', 'IN'),
(39, 'Bachelor of Information Systems Management (B.I.S.M)', 'Under Graduation', 'IN'),
(40, 'Bachelor of Laws (B.L)', 'Under Graduation', 'IN'),
(41, 'Bachelor of Library and Information Science (B.L.I.S)', 'Under Graduation', 'IN'),
(42, 'Bachelor of Labour Management (B.L.M)', 'Under Graduation', 'IN'),
(43, 'Bachelor Library Science (B.L.Sc)', 'Under Graduation', 'IN'),
(44, 'Bachelor of Literature (B.Lit)', 'Under Graduation', 'IN'),
(45, 'Bachelor of Medical Laboratory Technology (B.M.L.T)', 'Under Graduation', 'IN'),
(46, 'Bachelor of Mental Retardation (B.M.R)', 'Under Graduation', 'IN'),
(47, 'Bachelor of Medical Record Science (B.M.R.Sc)', 'Under Graduation', 'IN'),
(48, 'Bachelor in Mobility Science (B.M.Sc)', 'Under Graduation', 'IN'),
(49, 'Bachelor of Mobility Science (B.M.Sc)', 'Under Graduation', 'IN'),
(50, 'Bachelor of Medical Technology (B.M.T)', 'Under Graduation', 'IN'),
(51, 'Bachelor of Naturopathy and Yogic Sciences (B.N.Y.Sc)', 'Under Graduation', 'IN'),
(52, 'Bachelor of Occupational Therapy (B.O.T)', 'Under Graduation', 'IN'),
(53, 'Bachelor of Occupational Therapy (B.O.Th)', 'Under Graduation', 'IN'),
(54, 'Bachelor of Optometry and Vision Science (B.Optom)', 'Under Graduation', 'IN'),
(55, 'Bachelor of Physical Education (B.P.E)', 'Under Graduation', 'IN'),
(56, 'Bachelor Of Physical Education (B.P.Ed)', 'Under Graduation', 'IN'),
(57, 'Bachelor in Prosthetics and Orthotics (B.P.O)', 'Under Graduation', 'IN'),
(58, 'Bachelor of Public Relations (B.P.R)', 'Under Graduation', 'IN'),
(59, 'Bachelor of Physiotherapy (B.P.T)', 'Under Graduation', 'IN'),
(60, 'Bachelor of Pharmacy (B.Pharma)', 'Under Graduation', 'IN'),
(61, 'Bachelor of Rehabilitation Therapy (B.R.T)', 'Under Graduation', 'IN'),
(62, 'Bachelor of Science (B.S)', 'Under Graduation', 'IN'),
(63, 'Bachelor in Science Education (B.S.E)', 'Under Graduation', 'IN'),
(64, 'Bachelor of Speech Language & Audiology (B.S.L.A)', 'Under Graduation', 'IN'),
(65, 'Bachelor of Socio Legal Sciences Bachelor of Laws (B.S.L.LL.B)', 'Under Graduation', 'IN'),
(66, 'Bachelor of Siddha Medical Sciences (B.S.M.S)', 'Under Graduation', 'IN'),
(67, 'Bachelor Of Social Work (B.S.W)', 'Under Graduation', 'IN'),
(68, 'Bachelor of Science (B.Sc)', 'Under Graduation', 'IN'),
(69, 'Bachelor of Science Bachelor of Education (B.Sc.B.Ed)', 'Under Graduation', 'IN'),
(70, 'Bachelor of Science in Education (B.Sc.Ed)', 'Under Graduation', 'IN'),
(71, 'Bachelor of Tourism Administration (B.T.A)', 'Under Graduation', 'IN'),
(72, 'Basic Training Certificate (B.T.C)', 'Under Graduation', 'IN'),
(73, 'Bachelor of Technology (B.Tech)', 'Under Graduation', 'IN'),
(75, 'Bachelor of Unani Medicine & Surgery (B.U.M.S)', 'Under Graduation', 'IN'),
(76, 'Bachelor of Veterinary Science (B.V.Sc)', 'Under Graduation', 'IN'),
(77, 'Bachelor of Medicine (Bachelor of Medicine)', 'Under Graduation', 'IN'),
(78, 'Bachelor of Journalism and Mass Communication (BJMC)', 'Under Graduation', 'IN'),
(79, 'Diploma in Special Education (D.S.E (CP))', 'Under Graduation', 'IN'),
(80, 'Bachelor of Unani Medicine & Surgery (Kamil e Tob o Jarahat)', 'Under Graduation', 'IN'),
(81, 'Bachelor of Law (LL.B)', 'Under Graduation', 'IN'),
(82, 'Bachelor of Medicine Bachelor of Surgery (M.B.B.S)', 'Under Graduation', 'IN'),
(83, 'Master of Journalism and Mass Communication (MJMC)', 'Under Graduation', 'IN'),
(84, 'Doctor of Philosophy (Ph. D)', 'Under Graduation', 'IN'),
(85, 'Clinical Psychology (Psy.D (Cl.Psy))', 'Under Graduation', 'IN'),
(86, 'Under Graduate Basic Training (U.G.B.T)', 'Under Graduation', 'IN'),
(87, 'Under Graduate Training (U.G.T)', 'Under Graduation', 'IN'),
(88, 'Under Graduate Teacher Training (U.G.T.T)', 'Under Graduation', 'IN'),
(89, 'Under Graduate (UG)', 'Under Graduation', 'IN'),
(90, 'Master of Science (BOTANY)', 'Post Graduation', 'IN'),
(91, 'Diploma in Medical (D.M)', 'Post Graduation', 'IN'),
(92, 'Executive Fellow Program In Management (E.F.P.M)', 'Post Graduation', 'IN'),
(93, 'Executive Management Programme (E.M.P)', 'Post Graduation', 'IN'),
(94, 'NULL (EPGP)', 'Post Graduation', 'IN'),
(95, 'Fellow Programme in Management (F.P.M)', 'Post Graduation', 'IN'),
(96, 'FACULTY DEVELOPMENT PROGRAMME (FDP)', 'Post Graduation', 'IN'),
(97, 'Executive Fellow Programme in Management (FELLOWSHIP)', 'Post Graduation', 'IN'),
(98, 'FELLOW PROGRAMME IN MANAGEMENT (FELLOWSHIP)', 'Post Graduation', 'IN'),
(99, 'FELLOW PROGRAMME IN MANAGEMENT (FPM)', 'Post Graduation', 'IN'),
(100, 'Master of Law (LL.M)', 'Post Graduation', 'IN'),
(101, 'Master of Arts (M.A)', 'Post Graduation', 'IN'),
(102, 'Master of Arts (M.A. (SWDS))', 'Post Graduation', 'IN'),
(103, 'Master of Arts in Management (M.A.M)', 'Post Graduation', 'IN'),
(104, 'Master of Arts in Personal Management (M.A.P.M)', 'Post Graduation', 'IN'),
(105, 'Master of Arts (M.A.S.L.P)', 'Post Graduation', 'IN'),
(106, 'Master of Audiology & Speech Language Pathology (M.A.S.L.P)', 'Post Graduation', 'IN'),
(107, 'Master of Arts in Theatre & Television (M.A.T.T)', 'Post Graduation', 'IN'),
(108, 'Master of Architecture (M.Arch)', 'Post Graduation', 'IN'),
(109, 'Master of Business Administration (M.B.A)', 'Post Graduation', 'IN'),
(110, 'Master of Business Economics (M.B.E)', 'Post Graduation', 'IN'),
(111, 'Master of Business Laws (M.B.L)', 'Post Graduation', 'IN'),
(112, 'Master of Business Management (M.B.M)', 'Post Graduation', 'IN'),
(113, 'Master of Business Studies (M.B.S)', 'Post Graduation', 'IN'),
(114, 'Master of Computer Applications (M.C.A)', 'Post Graduation', 'IN'),
(115, 'Master of Communication & Journalism (M.C.J)', 'Post Graduation', 'IN'),
(116, 'Master of Comparative Laws (M.C.L)', 'Post Graduation', 'IN'),
(117, 'Master of Computer Management (M.C.M)', 'Post Graduation', 'IN'),
(118, 'Master of Corporate Secretaryship (M.C.S)', 'Post Graduation', 'IN'),
(119, 'Master of Chirurgical (M.Ch)', 'Post Graduation', 'IN'),
(120, 'Master of Commerce (M.Com)', 'Post Graduation', 'IN'),
(121, 'Doctor of Medicine (M.D)', 'Post Graduation', 'IN'),
(122, 'Sports Medicine (M.D)', 'Post Graduation', 'IN'),
(123, 'Management Development Programme (M.D.P)', 'Post Graduation', 'IN'),
(124, 'Master of Dental Surgery (M.D.S)', 'Post Graduation', 'IN'),
(125, 'Master of Design (M.Des)', 'Post Graduation', 'IN'),
(126, 'Master of Engineering (M.E)', 'Post Graduation', 'IN'),
(127, 'Master of Education (M.Ed)', 'Post Graduation', 'IN'),
(128, 'Master of education in Artificial Intelligence (M.Ed AI)', 'Post Graduation', 'IN'),
(129, 'Master of Fine Arts (M.F.A)', 'Post Graduation', 'IN'),
(130, 'Master of Finance & Control (M.F.C)', 'Post Graduation', 'IN'),
(131, 'Master of Film Management (M.F.M)', 'Post Graduation', 'IN'),
(132, 'Master of Financial Services (M.F.S)', 'Post Graduation', 'IN'),
(133, 'Master of Fishery Science (M.F.Sc)', 'Post Graduation', 'IN'),
(134, 'Master of Fishery Sciences (M.F.Sc)', 'Post Graduation', 'IN'),
(135, 'Master of Foreign Trade (M.F.T)', 'Post Graduation', 'IN'),
(136, 'Master of Hospital Administration (M.H.A)', 'Post Graduation', 'IN'),
(137, 'Master of Hospitality & Hotel Management (M.H.H.M)', 'Post Graduation', 'IN'),
(138, 'Master of Hospitality Management (M.H.M)', 'Post Graduation', 'IN'),
(139, 'Master of Human Resource Management (M.H.R.M)', 'Post Graduation', 'IN'),
(140, 'Master Of Health Science (M.H.Sc)', 'Post Graduation', 'IN'),
(141, 'Masters of Hospitality and Tourism Management (M.H.T.M)', 'Post Graduation', 'IN'),
(142, 'Master of International Business (M.I.B)', 'Post Graduation', 'IN'),
(143, 'Master of Information Management (M.I.M)', 'Post Graduation', 'IN'),
(144, 'Master of Journalism (M.J)', 'Post Graduation', 'IN'),
(145, 'Master of Laws (M.L)', 'Post Graduation', 'IN'),
(146, 'Master of Library and Information Science (M.L.I.Sc)', 'Post Graduation', 'IN'),
(147, 'Master of Labour Management (M.L.M)', 'Post Graduation', 'IN'),
(148, 'Master of Library Science (M.L.Sc)', 'Post Graduation', 'IN'),
(149, 'Master of Marketing Management (M.M.M)', 'Post Graduation', 'IN'),
(150, 'Master of Management Program (M.M.P)', 'Post Graduation', 'IN'),
(151, 'Master of Management Studies (M.M.S)', 'Post Graduation', 'IN'),
(152, 'Master of Occupational Theraphy (M.O.T)', 'Post Graduation', 'IN'),
(153, 'Master of Performing Arts (M.P.A)', 'Post Graduation', 'IN'),
(154, 'Master of Psychiatric Epidemiology (M.P.E)', 'Post Graduation', 'IN'),
(155, 'Master Of Physical Education (M.P.Ed)', 'Post Graduation', 'IN'),
(156, 'Master of Public Health (M.P.H)', 'Post Graduation', 'IN'),
(157, 'Masters Programme in International Business (M.P.I.B)', 'Post Graduation', 'IN'),
(158, 'Master of Performance Management (M.P.M)', 'Post Graduation', 'IN'),
(159, 'Diploma in Prosthetics & Orthotics (M.P.O)', 'Post Graduation', 'IN'),
(160, 'Masters in Public Systems Management (M.P.S.M)', 'Post Graduation', 'IN'),
(161, 'Master of Physiotheraphy (M.P.T)', 'Post Graduation', 'IN'),
(162, 'Master of Pharmacy (M.Pharma)', 'Post Graduation', 'IN'),
(163, 'Master of Philosophy (M.Phil)', 'Post Graduation', 'IN'),
(164, 'Master of Rehabilitation Science (M.R.Sc)', 'Post Graduation', 'IN'),
(165, 'M.S. in Library and Information Science (M.S)', 'Post Graduation', 'IN'),
(166, 'Master of Science (M.S)', 'Post Graduation', 'IN'),
(167, 'Master of Social Dynamics (M.S.D)', 'Post Graduation', 'IN'),
(168, 'Masters Programme In Sports Physiotheraphy (M.S.P.T)', 'Post Graduation', 'IN'),
(169, 'Master of Social Work (M.S.W)', 'Post Graduation', 'IN'),
(170, 'Master of Science (M.Sc)', 'Post Graduation', 'IN'),
(171, 'Master of Tourism Administrations (M.T.A)', 'Post Graduation', 'IN'),
(172, 'Master of Tourism Management (M.T.M)', 'Post Graduation', 'IN'),
(173, 'Master of Technology (M.Tech)', 'Post Graduation', 'IN'),
(174, 'Master of Veterinary Science (M.V.Sc)', 'Post Graduation', 'IN'),
(175, 'Doctor of Medicine Unani (Mahir e Tibb)', 'Post Graduation', 'IN'),
(176, 'Master of Business Administration (MBA)', 'Post Graduation', 'IN'),
(177, 'MANAGEMENT DEVELOPMENT PROGRAMEE (MDP)', 'Post Graduation', 'IN'),
(178, 'Master of Industrial Relation and Personal Management (MIR and PM)', 'Post Graduation', 'IN'),
(179, 'Master of Personnel Management (MPM)', 'Post Graduation', 'IN'),
(180, 'Master of Personal Management and Industrial Relation (MPM and IR)', 'Post Graduation', 'IN'),
(181, 'Post Graduate Diploma (P Diplomo)', 'Post Graduation', 'IN'),
(182, 'Post Graduate Diploma (P.G.D.D.R.M)', 'Post Graduation', 'IN'),
(183, 'Post Graduate Diploma (P.G.D.D.T.(MD:P&N))', 'Post Graduation', 'IN'),
(184, 'Post Graduate Diploma (P.G.D.E.I)', 'Post Graduation', 'IN'),
(185, 'Post Graduate Diploma (P.G.D.R.P)', 'Post Graduation', 'IN'),
(186, 'Post Graduate Diploma (P.G.D.S.E.(MR))', 'Post Graduation', 'IN'),
(187, 'Post Graduate Programme (P.G.P)', 'Post Graduation', 'IN'),
(188, 'Post Graduate (PG)', 'Post Graduation', 'IN'),
(189, 'Post Graduate Diploma (PG Diploma)', 'Post Graduation', 'IN'),
(190, 'Post Graduate Programme (PG Programme)', 'Post Graduation', 'IN'),
(191, 'Post Graduate Diploma (PGD)', 'Post Graduation', 'IN'),
(192, 'POST GRADUATE PROGRAME FOR EXECUTIVES (PGEXP)', 'Post Graduation', 'IN'),
(193, 'POST-GRADUATE PROGRAMME IN MANAGEMENT (PGP)', 'Post Graduation', 'IN'),
(194, 'POST GRADUATE PROGRAMME IN AGRIBUSINESS MANAGEMENT (PGP-ABM)', 'Post Graduation', 'IN'),
(195, 'PUBLIC MANAGEMENT AND POLICY (PGP-PMP)', 'Post Graduation', 'IN'),
(196, 'PGPX IN -VISIONARY LEADERSHIP IN MANUFACTURING (PGPEX-VLM)', 'Post Graduation', 'IN'),
(197, 'POST GRADUATE PROGRAME IN MANAGEMENT (PGPM)', 'Post Graduation', 'IN'),
(198, 'MANAGEMENT FOR EXECUTIVES (PGPX)', 'Post Graduation', 'IN'),
(199, 'Doctor of Philosophy (Ph. D)', 'Post Graduation', 'IN'),
(200, 'Doctor of Philosophy (Ph.D)', 'Post Graduation', 'IN'),
(201, 'Visual Information Processing (Visual Information Processing)', 'Post Graduation', 'IN'),
(202, 'Advanced Diploma (Advanced Diploma)', 'Diploma', 'IN'),
(203, 'Advanced Post Graduate Diploma (Advanced PG Diploma)', 'Diploma', 'IN'),
(204, 'Arts Teacher Diploma (ATD)', 'Diploma', 'IN'),
(205, 'Bachelor of Arts (B.A.S.L.P)', 'Diploma', 'IN'),
(206, 'Bachelor of Education (B.Ed)', 'Diploma', 'IN'),
(207, 'Bachelor of Education (B.Ed.Spl.Ed.(MD))', 'Diploma', 'IN'),
(208, 'Diploma in Banking Administration (D.B.A)', 'Diploma', 'IN'),
(209, 'Diploma in Education (D.B.Ed)', 'Diploma', 'IN'),
(210, 'Community Based Rehabilitation (D.C.B.R)', 'Diploma', 'IN'),
(211, 'Diploma in Early Childhood Care & Education (D.E.C.C.E)', 'Diploma', 'IN'),
(212, 'NULL (D.E.C.S.E)', 'Diploma', 'IN'),
(213, 'Diploma in Electrical Engineering (D.E.E)', 'Diploma', 'IN'),
(214, 'Diploma in Embedded Electronics Design (D.E.Ed)', 'Diploma', 'IN'),
(215, 'Diploma in Electronics & instrumentation Engineering (D.E.I.E)', 'Diploma', 'IN'),
(216, 'Diploma in Education (D.Ed)', 'Diploma', 'IN'),
(217, 'Diploma in Education (D.Ed(MR))', 'Diploma', 'IN'),
(218, 'Diploma in Education (D.Ed.(ASD))', 'Diploma', 'IN'),
(219, 'Diploma in Education (D.Ed.Q)', 'Diploma', 'IN'),
(220, 'Diploma in Education (D.Ed.Spl.Ed.(Db))', 'Diploma', 'IN'),
(221, 'Diploma in Education (D.Ed.Spl.Ed.(DHH))', 'Diploma', 'IN'),
(222, 'Diploma in Education (D.Ed.Spl.Ed.(VI))', 'Diploma', 'IN'),
(223, 'Diploma in Film Technology (D.F.Tech)', 'Diploma', 'IN'),
(224, 'Dynamic Graphics Project (D.G.P)', 'Diploma', 'IN'),
(225, 'Diploma in Hearing Aid Repair and Ear Mould Technology (D.H.A.R.E.M.T)', 'Diploma', 'IN'),
(226, 'Department of Human Services-Teleconference Mode (D.H.L.S)', 'Diploma', 'IN'),
(227, 'Diploma in Hearing Language and Speech (D.H.L.S)', 'Diploma', 'IN'),
(228, 'Diploma in Hearing, Language and Speech (D.H.L.S)', 'Diploma', 'IN'),
(229, 'INn Sign lang Interpreting (D.I.S.L.I)', 'Diploma', 'IN'),
(230, 'Diploma in International Trade (D.I.T)', 'Diploma', 'IN'),
(231, 'Diploma in Medical Laboratory Technology (D.M.L.T)', 'Diploma', 'IN'),
(232, 'Diploma in Media Planning and Buying (D.M.P.B)', 'Diploma', 'IN'),
(233, 'Diploma in Primary Education (D.P.E)', 'Diploma', 'IN'),
(234, 'Diploma in Physical Education (D.P.Ed )', 'Diploma', 'IN'),
(235, 'Diploma in Prosthetics and Orthotics (D.P.O)', 'Diploma', 'IN'),
(236, 'Diploma in Pharmacy (D.Pharm)', 'Diploma', 'IN'),
(237, 'Drug Rehabilitation Therapy (D.R.T)', 'Diploma', 'IN'),
(238, 'Diploma in Special Education (D.S.E)', 'Diploma', 'IN'),
(239, 'Diploma in Special Education (D.S.E (HI))', 'Diploma', 'IN'),
(240, 'Diploma in Technical Education (D.T.E)', 'Diploma', 'IN'),
(241, 'Diploma in Teacher Education (D.T.Ed)', 'Diploma', 'IN'),
(242, 'Diploma in Teacher Education (D.T.Ed AI)', 'Diploma', 'IN'),
(243, 'Diploma in Hearing Handicapped (D.T.Y.(DHH))', 'Diploma', 'IN'),
(244, 'Diploma in Vocational Rehabilitation (Mental Retardation) (D.V.R.(MR))', 'Diploma', 'IN'),
(245, 'Diploma in Vocational Training and Employment (D.V.T.E )', 'Diploma', 'IN'),
(246, 'NULL (D.V.T.E)', 'Diploma', 'IN'),
(247, 'Diploma in Yoga Education (D.Y.Ed)', 'Diploma', 'IN'),
(248, 'Diploma Courses (Diploma)', 'Diploma', 'IN'),
(249, 'Diploma in Construction Safety and Health (Diploma)', 'Diploma', 'IN'),
(250, 'Diploma in Fire Safety Management (Diploma)', 'Diploma', 'IN'),
(251, 'Diploma in Metallurgy (Diploma)', 'Diploma', 'IN'),
(252, 'Diploma in Ministry of Manpower (Diploma)', 'Diploma', 'IN'),
(253, 'Part-time Certificate/Diploma course in SQC and OR (Diploma)', 'Diploma', 'IN'),
(254, 'Diploma in Special Education (Diploma in Special Education)', 'Diploma', 'IN'),
(255, 'Higher Diploma in Footwear Technology (HDFT)', 'Diploma', 'IN'),
(256, 'International Diploma in Hotel Management (I.D.H.M)', 'Diploma', 'IN'),
(257, 'Junior Diploma (Jr.Diploma)', 'Diploma', 'IN'),
(258, 'Master of Arts (M.A.S.L.P)', 'Diploma', 'IN'),
(259, 'Bachelor of Medicine and Bachelor of Surgery (M.B.B.S)', 'Diploma', 'IN'),
(260, 'Master of Education (M.Ed)', 'Diploma', 'IN'),
(261, 'Master of Philosophy (M.Phil.(R.P.))', 'Diploma', 'IN'),
(262, 'Post Graduate Diploma (P. G. Diploma)', 'Diploma', 'IN'),
(263, 'Post Graduate Diploma in Business Management (P.G.D.B.M)', 'Diploma', 'IN'),
(264, 'Post Graduate Diploma in Computer Application (P.G.D.C.A)', 'Diploma', 'IN'),
(265, 'Post Graduate Diploma (P.G.D.D.R.M)', 'Diploma', 'IN'),
(266, 'Post Graduate Diploma (P.G.D.M)', 'Diploma', 'IN'),
(267, 'post graduate diploma in management (P.G.D.M)', 'Diploma', 'IN'),
(268, 'Post Graduate Diploma (P.G.D.S.E.(MD:P&N))', 'Diploma', 'IN'),
(269, 'Post Graduate Diploma (PG Diploma)', 'Diploma', 'IN'),
(270, 'POST GRADUATE DIPLOMA IN COMPUTER AIDED MANAGEMENT (PGDCM)', 'Diploma', 'IN'),
(271, 'POST GRADUATE DIPLOMA IN HUMAN RESOURCE MANAGEMENT (PGDHRM)', 'Diploma', 'IN'),
(272, 'post graduate diploma in management (PGDM)', 'Diploma', 'IN'),
(273, 'Senior Diploma (Sr.Diploma)', 'Diploma', 'IN'),
(274, 'Under Graduate Diploma in Physical Education (U.G.D.P.Ed)', 'Diploma', 'IN');";
        DB::unprepared($sql);
    }
}
