version : '3'

networks:
    dompp:
        name: dompp
        external: true

services:
  laravel.test:
        build:
            context: ./vendor/laravel/sail/runtimes/8.1
            dockerfile: Dockerfile
            args:
                WWWGROUP: 1000
        image: sail-8.1/app
        ports:
            - 8001:80
        environment:
            WWWUSER: 1000
            LARAVEL_SAIL: 1
        volumes:
            - .:/var/www/html
        # depends_on:
        #     - mysql
        external_links:
            - mysql:mysql
        networks:
            - dompp
    
#   mysql:
#     image: mysql:latest
#     container_name: dev_mysql
#     volumes:
#       - ../../mysql:/var/lib/mysql
#     environment:
#       MYSQL_USER: root
#       MYSQL_PASSWORD: root
#       MYSQL_ROOT_PASSWORD: root
#       MYSQL_DATABASE: default_schema
#     ports:
#         - 3306:3306
#     networks:
#       - sthub

#   phpmyadmin:
#     image: phpmyadmin/phpmyadmin
#     container_name: dev_pma
#     links:
#       - mysql
#     environment:
#       PMA_HOST: mysql
#       PMA_PORT: 3306
#       PMA_ARBITRARY: 1
#       UPLOAD_LIMIT: 300M
#     restart: always
#     volumes:
#       - ../../phpmyadmin:/var/lib/mysql
#     ports:
#       - 8083:80
#     networks:
#       - sthub