<template>
    <div>
        <div>{{ category_name }}</div>
        <nav-tabs :tabs="tabs" :initial-tab="initialTab">
            <template slot="tab-heading-posts">
                {{ "Posts" }}
            </template>
            <template slot="tab-panel-posts">
                <div v-if="!posts.length" class="row">
                    <div class="col-md-5 center-col">
                        <div class="sh_kn">
                            <img src="/images/noun_knowledge.svg" />
                            <h4>Share Your Knowledge</h4>
                            <a href="/share-your-knowledge">Get Started</a>
                        </div>
                    </div>
                </div>
                <div v-else class="row">
                    <div class="col-md-5 center-col">
                        <div v-for="(post, index) in posts" :key="index">
                            <post-card :post="post" />
                        </div>
                    </div>
                </div>
            </template>
            <template slot="tab-heading-interests">
                {{ "Interests" }}
            </template>
            <template slot="tab-panel-interests">
                <div class="user_interest">
                    <h4>Your Interest</h4>
                    <div class="user_int">
                        <div class="user_int_text">
                            <p v-show="user.id === AuthUser.id">
                                This data is generated by your interaction with
                                posts,hence the more you interect with posts the
                                more precise this data is.
                            </p>

                            <div class="progess_bar">
                                <div
                                    v-for="(interest, index) in interests"
                                    :key="index"
                                    class="cojl text-center"
                                >
                                    <radial-progress-bar
                                        :diameter="150"
                                        :completed-steps="
                                            interest_enable
                                                ? interest.percent
                                                : 0
                                        "
                                        :total-steps="100"
                                        :start-color="'#00BFFF'"
                                        :stop-color="'#000080'"
                                        :inner-stroke-color="'#B0E0E6'"
                                    >
                                        <p>
                                            {{
                                                interest_enable
                                                    ? parseInt(interest.percent)
                                                    : 0
                                            }}%
                                        </p>
                                    </radial-progress-bar>
                                    <p>{{ interest.name }}</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </template>
        </nav-tabs>
    </div>
</template>
<style scoped></style>
<script>
import SiteFooter from "../footer/SiteFooter";
import NavTabs from "../../components/NavTabs.vue";
export default {
    components: {
        SiteFooter,
        NavTabs
    },
    data() {
        return {
            category_name: "",
            email: "",
            description: "",
            showLoader: false
        };
    },
    mounted() {
        console.log(this.$route.params.url);
        this.axios
            .get("/api/get-category-details/" + this.$route.params.url)
            .then(resp => {
                this.category_name = resp.data.success.category.name;
            });
    },
    methods: {
        handleSubmit() {
            this.$validator.validate().then(valid => {
                if (valid) {
                    this.axios
                        .post("/api/contactus", {
                            name: this.AuthUser
                                ? this.AuthUser.full_name
                                : this.name,
                            email: this.AuthUser
                                ? this.AuthUser.email
                                : this.email,
                            description: this.description
                        })
                        .then(resp => {
                            window.location.href = "/";
                        })
                        .catch(err => {});
                }
            });
        }
    }
};
</script>
