<template>
<div class="row">
            <form>
                <input name="__RequestVerificationToken" type="hidden" value="fU3_ynE3ZWQ8SbARiKw6-ilIhoOK0WCkYBNdrEa386lTZ2vInPXyRgok-AYyYMY_ifMmOjdPUHU1br1EGHH2u59n4Vr_ZzHQKLqMTVjjx8I1">
                <div class="col-sm-12 col-md-12 col-xs-12">
                    <div class="inner-title-left instituteList_breadbumb">
                        <p>List of Institutes/Universities-Discipline Wise</p>
                        <h2>Explore Our Programs From All Across INDIA</h2>
                    </div>
                </div>
                <div class="clearfix"></div>
                <div class="col-md-2 col-sm-4 col-xs-12">
                    <div class="form-group institutesDropdown_slider">
                        <label for="sel1" class="white_text">Discipline</label>
                        <select class="form-control" id="drpDiscipline" name="Discipline_ID" required=""><option value="">All</option>
                            <option value="8">Architecture</option>
                            <option value="9">Arts</option>
                            <option value="10">Commerce</option>
                            <option value="60">Dental</option>
                            <option value="61">Design</option>
                            <option value="11">Engineering</option>
                            <option value="12">Humanities</option>
                            <option value="13">Law</option>
                            <option value="14">Management</option>
                            <option value="15">Medical</option>
                            <option value="62">Optometry</option>
                            <option value="16">Pharmacy</option>
                            <option value="17">Science</option>
                            </select>
                    </div>
                </div>
                <div class="col-md-2 col-sm-4 col-xs-12">
                    <div class="form-group institutesDropdown_slider">
                        <label for="sel1" class="white_text">Program Level</label>
                        <select class="form-control" id="drpProgramLevel" name="ProgrammeLevel_ID" required=""><option value="">All</option>
                            <option value="13">Diploma</option>
                            <option value="18">Dual Bachelors And Masters Degree</option>
                            <option value="15">Dual Bachelors Degree</option>
                            <option value="19">Dual Masters</option>
                            <option value="21">Integrated PhD</option>
                            <option value="20">PhD</option>
                            <option value="16">Post Graduate (PG)</option>
                            <option value="17">Post Graduate Diplomas</option>
                            <option value="14">Under Graduate (UG)</option>
                            </select>
                    </div>
                </div>
                <div class="col-md-3 col-sm-4 col-xs-12">
                    <div class="form-group institutesDropdown_slider">
                        <label for="sel1" class="white_text">Nature of Courses</label>
                        <select class="form-control" id="drpNatureofcourse" name="Natureofcourse" required=""><option value="">All</option>
                    <option value="120">B. Pharma + MBA (Integrated)</option>
                    <option value="157">B.A + L.L B</option>
                    <option value="158">B.B.A. + L.L.B.</option>
                    <option value="89">B.Com + LLB (Hons. Integrated)</option>
                    <option value="91">B.Tech + M.Tech (Integrated)</option>
                    <option value="92">B.Tech + MBA (Integrated)</option>
                    <option value="94">BA + LLB (Hons. Integrated)</option>
                    <option value="95">BA + LLB (Integrated)</option>
                    <option value="160">Bachelor in Clinical Optometry (B.Optom.)</option>
                    <option value="8">Bachelor in Multimedia Communication(BMMC)</option>
                    <option value="9">Bachelor of Architecture (B.Arch)</option>
                    <option value="13">Bachelor of Arts (BA - 3 Continent)</option>
                    <option value="11">Bachelor of Arts (BA)</option>
                    <option value="14">Bachelor of Arts (Honors)</option>
                    <option value="15">Bachelor of Business Administration (BBA)</option>
                    <option value="126">Bachelor of Business Administration (BBA) (Honors)</option>
                    <option value="16">Bachelor of Commerce (B.Com)</option>
                    <option value="17">Bachelor of Commerce (Honors)</option>
                    <option value="20">Bachelor of Computer Application (BCA - Evening)</option>
                    <option value="21">Bachelor of Computer Application (BCA)</option>
                    <option value="22">Bachelor of Design (B.Des)</option>
                    <option value="24">Bachelor of Education (B.Ed)</option>
                    <option value="26">Bachelor of Engineering (B.E.)</option>
                    <option value="27">Bachelor of Environment Management (BEM)</option>
                    <option value="28">Bachelor of Fashion Technology (BFT)</option>
                    <option value="29">Bachelor of Fine Arts (BFA)</option>
                    <option value="30">Bachelor of Hotel Management</option>
                    <option value="31">Bachelor of Hotel Management &amp; Catering Technology (BHM &amp; CT)</option>
                    <option value="32">Bachelor of Interior Design</option>
                    <option value="33">Bachelor of Law (LLB)</option>
                    <option value="127">Bachelor of Library and Information Science (BLIS)</option>
                    <option value="34">Bachelor of Management Studies (BMS)</option>
                    <option value="35">Bachelor of Occupational Therapy</option>
                    <option value="36">Bachelor of Pharmacy (B.Pharm)</option>
                    <option value="37">Bachelor of Physical Education &amp; Sports</option>
                    <option value="38">Bachelor of Physiotherapy</option>
                    <option value="39">Bachelor of Planning</option>
                    <option value="124">Bachelor of Public Health</option>
                    <option value="40">Bachelor of Science (B.Sc)</option>
                    <option value="41">Bachelor of Science (Honors)</option>
                    <option value="43">Bachelor of Social Work (BSW)</option>
                    <option value="44">Bachelor of Statistics</option>
                    <option value="45">Bachelor of Technology (B.Tech)</option>
                    <option value="49">Bachelor of Vocation (B.Voc.)</option>
                    <option value="97">BBA + LLB  (Integrated)</option>
                    <option value="98">BBA + LLB (Hons. Integrated)</option>
                    <option value="99">BBA + MBA (Integrated)</option>
                    <option value="100">BCA + MCA (Intergrated)</option>
                    <option value="101">BSC + MSC (Intergrated)</option>
                    <option value="152">Diploma</option>
                    <option value="159">Doctor of Pharmacy</option>
                    <option value="154">Doctor of Pharmacy (Post Baccalaureate)</option>
                    <option value="50">Executive MBA (EMBA)</option>
                    <option value="102">M.Pharm + MBA (Integrated)</option>
                    <option value="103">M.Phil. + Ph.D (Integrated)</option>
                    <option value="156">M.Tech + PhD (Integrated)</option>
                    <option value="51">Master Degree in Hospital Management (MDHM)</option>
                    <option value="52">Master of Architecture (M.Arch)</option>
                    <option value="53">Master of Arts (M.A.)</option>
                    <option value="55">Master of Business Administration (MBA - International)</option>
                    <option value="56">Master of Business Administration (MBA)</option>
                    <option value="57">Master of Commerce (M.Com)</option>
                    <option value="58">Master of Computer Application (MCA)</option>
                    <option value="60">Master of Design (M.Des)</option>
                    <option value="61">Master of Education (M.Ed)</option>
                    <option value="63">Master of Hospital Administration</option>
                    <option value="64">Master of Human Resource Management</option>
                    <option value="65">Master of Interior Design</option>
                    <option value="67">Master of Law (LLM)</option>
                    <option value="68">Master of Library and Information Science (MLIS)</option>
                    <option value="161">Master of Optometry (M.Optom.)</option>
                    <option value="70">Master of Pharmacy (M.Pharm)</option>
                    <option value="71">Master of Philosophy (M.Phil)</option>
                    <option value="72">Master of Physical Education (MPEd)</option>
                    <option value="74">Master of Public Health (MPH)</option>
                    <option value="75">Master of Science (M.Sc)</option>
                    <option value="76">Master of Social Work (MSW)</option>
                    <option value="79">Master of Technology (M.Tech)</option>
                    <option value="80">Master of Travel &amp; Tourism Management</option>
                    <option value="81">Masters (MS)-Research</option>
                    <option value="82">Masters in Mass Communication (MMC)</option>
                    <option value="84">Masters of Physiotherapy (MP)</option>
                    <option value="87">Ph.D</option>
                    <option value="107">Post Graduate Diploma in Management(PGDM)</option>
                    <option value="108">Post Graduate Diploma(PGD)</option>
                    </select>
                </div>
            </div>
                <div class="col-md-2 col-sm-4 col-xs-12">
                    <div class="form-group institutesDropdown_slider">
                        <label for="sel1" class="white_text">Branch/Subjects</label>
                        <select class="form-control" id="drpBranch" name="CourseOfStudy" required=""><option value="">All</option>
<option value="1194"> Astronomy, Astrophysics and Space Engineering</option>
<option value="1196"> Economics, Psychology, English, Philosophy, Sociology, History</option>
<option value="1193"> Electrical Engineering with specialisation in Communication &amp; Signal Processing</option>
<option value="1192"> Electrical Engineering with specialisation in VLSI Design and Nanoelectronics</option>
<option value="1150"> Mechanical Engineering (Design)</option>
<option value="1165">Access to Justice</option>
<option value="2">Accounting and Finance</option>
<option value="3">Actuarial Science</option>
<option value="1287">Advanced Manufacturing and Design</option>
<option value="8">Advertising and Marketing Management</option>
<option value="10">Aeronautical Engineering</option>
<option value="13">Aerospace Engineering</option>
<option value="17">Agri Business</option>
<option value="24">Agricultural Economics</option>
<option value="25">Agricultural Engineering</option>
<option value="1106">Agricultural Extension and Communication</option>
<option value="26">Agricultural Meteorology</option>
<option value="1114">Agricultural Microbiology</option>
<option value="27">Agriculture</option>
<option value="1185">Agriculture &amp; Food Business</option>
<option value="29">Agriculture and Food Business</option>
<option value="30">Agriculture Engineering</option>
<option value="31">Agroforestry</option>
<option value="32">Agronomy</option>
<option value="35">Airport and Aviation Business Management</option>
<option value="1321">Alternate Hydro Energy Systems</option>
<option value="51">Alternative Dispute Resolution</option>
<option value="52">Analytical Chemistry</option>
<option value="1096">Anasthesia Techology</option>
<option value="53">Anatomy</option>
<option value="54">Ancient Indian History, Culture and Archealogy</option>
<option value="56">Animal Biology and Biotechnology</option>
<option value="57">Animation</option>
<option value="58">Animation and Graphic Design</option>
<option value="59">Animation with International Moving Image Society, UK (Chartered Body)</option>
<option value="60">Anthropology</option>
<option value="61">Applicable Mathematics</option>
<option value="63">Applied Chemistry</option>
<option value="64">Applied Chemistry and Polymer Technology</option>
<option value="66">Applied Electronics</option>
<option value="68">Applied Geochemistry</option>
<option value="69">Applied Geology</option>
<option value="70">Applied Linguistics</option>
<option value="71">Applied Mathematics</option>
<option value="72">Applied Microbiology</option>
<option value="73">Applied Philosophy</option>
<option value="74">Applied Physics</option>
<option value="75">Applied Psychology</option>
<option value="76">Applied Psychology (Clinical Psychology)</option>
<option value="78">Applied Psychology (Counseling Psychology)</option>
<option value="1315">Applied Science &amp; Engineering</option>
<option value="81">Applied Statistics</option>
<option value="82">Apprel and Textile Science</option>
<option value="83">Aquaculture</option>
<option value="84">Arabic</option>
<option value="86">Architectural Design</option>
<option value="87">Architecture</option>
<option value="88">Architecture and Planning</option>
<option value="89">Architecture and Regional Planning</option>
<option value="93">Artificial Intelligence</option>
<option value="94">Arts</option>
<option value="96">Astronomy</option>
<option value="97">Atmosphere and Ocean Sciences</option>
<option value="1341">Audiology</option>
<option value="1363">AUDIOLOGY AND SPEECH LANGUAGE PATHOLOGY (BASLP)</option>
<option value="99">Automobile Engineering</option>
<option value="101">Automotive Electronics</option>
<option value="102">Automotive Engineering</option>
<option value="104">Automotive Technology</option>
<option value="1274">Autonomous Unmanned Vehicle Technologies</option>
<option value="105">Aviation Management</option>
<option value="106">Avionics</option>
<option value="107">B. Design - (Product design / Interior design)</option>
<option value="116">Bachelor of Arts and Bachelor of Laws</option>
<option value="119">Bachelor of Arts and Bachelor of Laws Honors</option>
<option value="120">Bachelor of Business Administration and Bachelor of Laws</option>
<option value="122">Bachelor of Business Administration and Bachelor of Laws Honors</option>
<option value="123">Banking and Finance</option>
<option value="124">Banking and Insurance</option>
<option value="127">Basic Sciences</option>
<option value="131">Bengali</option>
<option value="1091">Bharathanatyam </option>
<option value="132">Big Data Analytics</option>
<option value="135">Bio Science</option>
<option value="136">Bio Technology</option>
<option value="137">Bio-Informatics</option>
<option value="138">Bio-Medical Engineering</option>
<option value="139">Biochemical</option>
<option value="140">Biochemical Engineering</option>
<option value="141">Biochemistry</option>
<option value="143">Bioinformatics</option>
<option value="144">Biological Sciences</option>
<option value="146">Biomedical Engineering (BME)</option>
<option value="147">Biomedical Genetics</option>
<option value="148">Biomedical Instrumentation</option>
<option value="1397">Biomedical Signal Processing &amp; Instrumentation</option>
<option value="1338">Bioprocess Engineering</option>
<option value="149">Bioprocess Technology</option>
<option value="150">BioScience and Bio Engineering</option>
<option value="151">Biosciences and Biomedical Engineering</option>
<option value="152">Biostatistics</option>
<option value="153">Biotechnology</option>
<option value="155">Biotechnology (spec. in Genetic Engineering )</option>
<option value="156">Biotechnology (spec. in Regenerative Medicine )</option>
<option value="157">Biotechnology and Biochemical Engineering</option>
<option value="1387">Biotechnology with Artificial Intelligence &amp; Machine Learning</option>
<option value="163">Botany</option>
<option value="166">Business Administration</option>
<option value="167">Business Analytics</option>
<option value="168">Business Development</option>
<option value="170">Business Management</option>
<option value="172">Business Process Services (BPS)</option>
<option value="165">Business Studies</option>
<option value="173">CA</option>
<option value="174">CAD</option>
<option value="175">CAD / CAM</option>
<option value="1330">CAD, CAM &amp; Robotics</option>
<option value="1095">Cardiac Care Technology</option>
<option value="1355">Cardiac Perfusion Technology (CPT)</option>
<option value="1136">Cardiovascular Technology</option>
<option value="177">Career Guidance</option>
<option value="178">Career Guidance and Councelling</option>
<option value="179">Catering Science and Hotel Management</option>
<option value="181">Centre for Oceans, Rivers, Atmosphere and Land Sciences Earth System Science and Technology</option>
<option value="1312">Centre for Transportation (CTRANS)</option>
<option value="182">Ceramic</option>
<option value="187">Chemical and Biochemical Engineering</option>
<option value="188">Chemical Engineering</option>
<option value="191">Chemical Sciences</option>
<option value="193">Cheminformatics</option>
<option value="194">Chemistry</option>
<option value="1166">Children &amp; Families</option>
<option value="200">Cinema and Television</option>
<option value="201">Civil</option>
<option value="203">Civil and Environmental Engineering</option>
<option value="205">Civil Engineering</option>
<option value="1148">Civil Engineering (Infrastructure Engineering &amp; Management)</option>
<option value="208">Civil Engineering and Structural Engineering</option>
<option value="209">Civil Engineering and Transportation Engineering</option>
<option value="210">Civil Engineering Construction Engineering and Management</option>
<option value="211">Civil Engineering Environmental Engineering and Management</option>
<option value="212">Civil Engineering Geotechnical Engineering</option>
<option value="213">Civil Engineering Hydraulic and Water Resources Engineering</option>
<option value="1386">Civil with Artificial Intelligence &amp; Machine Learning</option>
<option value="1163">Climate Change and Sustainability Studies</option>
<option value="217">Climate Sciences</option>
<option value="1256">Climate Studies</option>
<option value="1271">Clinical Embryology</option>
<option value="219">Clinical Research</option>
<option value="221">Cloud and Information Security integrated with KPMG Certified Cyber Security Professional</option>
<option value="222">Cloud Computing</option>
<option value="227">Cognitive Sciences</option>
<option value="228">Commerce</option>
<option value="1376">Commerce and Management</option>
<option value="1395">Commercial Photography</option>
<option value="1399">Commercial Photography &amp; Cinematography</option>
<option value="229">Communication</option>
<option value="230">Communication and Journalism</option>
<option value="231">Communication and Signal Processing (EE)</option>
<option value="232">Communication Engineering</option>
<option value="233">Communication System Engineering</option>
<option value="1132">Community Development</option>
<option value="235">Community Science (Honors)</option>
<option value="236">Comparative Literature</option>
<option value="239">Computational Design</option>
<option value="1368">Computational Engineering &amp; Networking</option>
<option value="1377">Computational Neuroscience</option>
<option value="241">Computer</option>
<option value="1351">Computer Aided Structural Analysis and Design</option>
<option value="242">Computer and Communication Engineering</option>
<option value="244">Computer Applications</option>
<option value="245">Computer Engineering</option>
<option value="246">Computer Engineering (Cloud Technology and Mobile Application)</option>
<option value="248">Computer Integrated Design and Manufacturing</option>
<option value="251">Computer Science</option>
<option value="1342">Computer Science &amp; Engineering with a Specialization in Blockchain Technology</option>
<option value="1348">Computer Science &amp; Engineering with specialization in Cyber Physical Systems</option>
<option value="252">Computer Science (Data Science)</option>
<option value="1184">Computer Science and Business System</option>
<option value="253">Computer Science and Engineering</option>
<option value="254">Computer Science and Engineering (Spec. in Artificial Intelligence and Machine Learning)</option>
<option value="255">Computer Science and Engineering (Spec. in Big Data Analytics)</option>
<option value="256">Computer Science and Engineering (Spec. in Bioinformatics)</option>
<option value="259">Computer Science and Engineering (Spec. in Cyber Security)</option>
<option value="260">Computer Science and Engineering (Spec. in Data Analytics)</option>
<option value="261">Computer Science and Engineering (Spec. in Information Security)</option>
<option value="262">Computer Science and Engineering (Spec. in Information Technology and Entrepreneurship)</option>
<option value="263">Computer Science and Engineering (Spec. in Information Technology)</option>
<option value="264">Computer Science and Engineering (Spec. in Internet of Things (IOT))</option>
<option value="1375">Computer Science and IT</option>
<option value="276">Computer Science and Technology</option>
<option value="278">Computer Technology</option>
<option value="281">Computing and Electrical Engineering</option>
<option value="283">Constitutional Law</option>
<option value="290">Construction Technology and Management</option>
<option value="291">Control and Automation</option>
<option value="292">Control and Instrumentation</option>
<option value="294">Control Systems</option>
<option value="295">Corporate Accounting with CMA USA integration</option>
<option value="297">Corporate Finance Integrated with CPA, USA + EA, USA</option>
<option value="298">Corporate Law</option>
<option value="299">Corporate Secretaryship</option>
<option value="300">Costume Design and Fashion</option>
<option value="1177">Counselling</option>
<option value="1167">Criminology &amp; Justice</option>
<option value="303">Cryogenic Engineering</option>
<option value="304">Culinary Arts</option>
<option value="305">Cyber Forensics and Information Security</option>
<option value="1285">Cyber Physical Systems</option>
<option value="306">Cyber Security</option>
<option value="1262">Cyber Security and Cyber Law</option>
<option value="1378">Cyber Security Systems and Networks</option>
<option value="1168">Dalit &amp; Tribal Studies and Action</option>
<option value="309">Dance</option>
<option value="311">Data Analytics</option>
<option value="1286">Data and Computational Science</option>
<option value="312">Data Science</option>
<option value="314">Data Science and Business Analytics</option>
<option value="315">Data Sciences and Data Analytics</option>
<option value="316">Database Systems</option>
<option value="1374">Deglutology and Swallowing Disorders</option>
<option value="1276">Dental Mechatronics</option>
<option value="317">Design</option>
<option value="1419">Design &amp; Manufacturing</option>
<option value="319">Design Engineering</option>
<option value="1174">Development Policy, Planning and Practice</option>
<option value="320">Development Studies</option>
<option value="1357">Diabetes Sciences (DBS)</option>
<option value="1085">Dialysis Technology</option>
<option value="1356">Dialysis Therapy (DIT)</option>
<option value="1318">Digital &amp; Cyber Forensic</option>
<option value="322">Digital Animation</option>
<option value="1265">Digital Humanities</option>
<option value="324">Digital System</option>
<option value="325">Digital Systems and Signal Processing</option>
<option value="1298">Diploma of Pharmacy</option>
<option value="1169">Disability Studies &amp; Action</option>
<option value="1173">Disaster Management</option>
<option value="1314">Disaster Mitigation &amp; Management</option>
<option value="1337">Disaster Mitigation and Management</option>
<option value="339">Drug Regulatory Affairs</option>
<option value="342">Dyestuff Technology</option>
<option value="343">E-Commerce</option>
<option value="344">E-Learning Technology</option>
<option value="347">Earth Sciences</option>
<option value="1302">Earthquake Engineering</option>
<option value="1410">ECE with Internet of Things (IoT)</option>
<option value="1358">Echocardiography Technology (ECT)</option>
<option value="1101">Ecocardiography</option>
<option value="1178">Ecology, Environment and Sustainable Development</option>
<option value="349">Econometrics</option>
<option value="350">Economics</option>
<option value="1408">Economics, Statistics, Mathematics</option>
<option value="1126">Ecosophical Aesthetics</option>
<option value="355">Education</option>
<option value="356">Education (Elementary)</option>
<option value="358">Education Studies</option>
<option value="1411">EEE with Robotics and Automation</option>
<option value="1328">Electric Drives &amp; Power Electronics</option>
<option value="365">Electrical and Electronics Engineering</option>
<option value="366">Electrical Engineering</option>
<option value="367">Electrical Engineering (Instrumentation Engineering)</option>
<option value="1146">Electrical Engineering (Power System)</option>
<option value="368">Electrical Engineering (Spec. in VLSI)</option>
<option value="369">Electrical Engineering and Power Electronics and Drives</option>
<option value="370">Electrical Engineering Control System Engineering</option>
<option value="371">Electrical Engineering Instrumentation and Signal Processing</option>
<option value="1421">Electrical Engineering with specialisation in Signal Processing and Communication</option>
<option value="375">Electronics</option>
<option value="1349">Electronics &amp; Computer Engineering</option>
<option value="1181">Electronics - VLSI Design</option>
<option value="376">Electronics and Communication</option>
<option value="378">Electronics and Communication Engineering</option>
<option value="379">Electronics and Communication Engineering (Spec. in Communication System)</option>
<option value="1389">Electronics and Communication Engineering (Spec. in Medical Electronics)</option>
<option value="381">Electronics and Communication Engineering (spl. In Biomedical Engineering)</option>
<option value="384">Electronics and Communication Engineering (spl. In Micro Electronic Systems and Embedded Technology)</option>
<option value="1388">Electronics and Communication Engineering with Artificial Intelligence &amp; Machine Learning</option>
<option value="385">Electronics and communication systems</option>
<option value="387">Electronics and Communication with (spl. In VLSI)</option>
<option value="389">Electronics and Control Engineering</option>
<option value="390">Electronics and Design</option>
<option value="392">Electronics and Electrical Communication Engineering Microelectronics and VLSI Design</option>
<option value="393">Electronics and Electrical Communication Engineering RF and Microwave Engineering</option>
<option value="396">Electronics and Electrical Engineering</option>
<option value="397">Electronics and Instrumentation</option>
<option value="398">Electronics and Instrumentation Engineering</option>
<option value="399">Electronics and Telecommunication</option>
<option value="400">Electronics and Telecommunication Engineering</option>
<option value="1072">Electronics Design &amp; Technology</option>
<option value="401">Electronics Engineering</option>
<option value="403">Electronics Science</option>
<option value="407">Embedded Control System</option>
<option value="408">Embedded System and Technologies</option>
<option value="410">Embedded Systems Engineering</option>
<option value="1362">Emergency Medical Tech</option>
<option value="1267">Emergency Medicine</option>
<option value="1401">Emerging Technologies</option>
<option value="1404">Emerging Technologies in Management</option>
<option value="413">Energy and Environmental Engineering</option>
<option value="414">Energy and Infrastructure Management</option>
<option value="415">Energy Engineering</option>
<option value="416">Energy Engineering (Spec. in Materials)</option>
<option value="417">Energy Science and Engineering</option>
<option value="419">Energy Studies</option>
<option value="420">Energy Systems (Focused on Solar Energy)</option>
<option value="422">Engineering</option>
<option value="424">Engineering Design</option>
<option value="427">Engineering Physics</option>
<option value="428">Engineering Science</option>
<option value="430">English</option>
<option value="1379">English and Languages</option>
<option value="434">English Language Studies</option>
<option value="435">Entomology</option>
<option value="436">Entrepreneurship</option>
<option value="1145">Entrepreneurship &amp; International Trade</option>
<option value="437">Entrepreneurship and Family Business</option>
<option value="1134">Environment &amp; Occupational Health</option>
<option value="439">Environment and Water Resource Engineering</option>
<option value="440">Environment Science</option>
<option value="1075">Environmental chemistry</option>
<option value="441">Environmental Engineering</option>
<option value="442">Environmental Management</option>
<option value="1322">Environmental Management of Rivers and Lakes</option>
<option value="1117">Environmental Science</option>
<option value="443">Environmental Science and Engineering</option>
<option value="445">Environmental Sciences</option>
<option value="446">Environmental Studies</option>
<option value="1100">Epidemology</option>
<option value="447">European Studies</option>
<option value="1137">Exercise &amp; Sports Sciences</option>
<option value="450">Extension Education</option>
<option value="451">Extension Education and Communication Management</option>
<option value="453">Family Business and Entrepreneurship</option>
<option value="455">Family Resource Management</option>
<option value="456">Farm Machinery and Power Engineering</option>
<option value="459">Fashion Design</option>
<option value="462">Fashion Retail Management</option>
<option value="463">Fashion Technology</option>
<option value="464">Fibres and Textile Processing Technology</option>
<option value="465">Film and Television Production</option>
<option value="466">Film and TV Production</option>
<option value="467">Finance</option>
<option value="468">Finance and Accounting</option>
<option value="470">Finance and Computer Applications</option>
<option value="471">Finance and HR</option>
<option value="473">Financial Analysis with KPMG International Accounting Practices</option>
<option value="474">Financial Economics</option>
<option value="1402">Financial Investment Analysis</option>
<option value="475">Financial Management</option>
<option value="476">Financial Markets</option>
<option value="479">Financial Technology</option>
<option value="480">Fine Arts</option>
<option value="481">Flim Technology</option>
<option value="482">Floriculture and Landscape Architecture</option>
<option value="483">Floriculture and Landscaping</option>
<option value="485">Food and Nutrition</option>
<option value="486">Food and Nutritional Biotechnology</option>
<option value="487">Food Biotechnology</option>
<option value="488">Food Engineering and Technology</option>
<option value="490">Food Processing Technology</option>
<option value="492">Food Safety and Quality Management</option>
<option value="1113">Food Science and Nutrition</option>
<option value="494">Food Science and Technology</option>
<option value="495">Food Science Technology</option>
<option value="496">Food Technology</option>
<option value="497">Food Technology</option>
<option value="1293">Food, Nutrition &amp; Dietetics</option>
<option value="1354">Food, Nutrition and Dietetics</option>
<option value="1125">Foreign Languages &amp; Intercultural Studies</option>
<option value="1272">Forensic Odontology</option>
<option value="499">Forensic Science</option>
<option value="500">Forensic Sciences</option>
<option value="501">Forest Genetic Resources</option>
<option value="502">Forestry</option>
<option value="504">French</option>
<option value="506">Fruit Science</option>
<option value="507">General</option>
<option value="508">General Management</option>
<option value="509">Genetic Engineering</option>
<option value="510">Genetics</option>
<option value="511">Genetics and Plant Breeding</option>
<option value="513">Geo Informatics and Remote Sensing</option>
<option value="1200">Geo-exploration and Petroleum Geo-sciences</option>
<option value="514">Geo-informatics</option>
<option value="1156">Geo-Technical and Geo-Environmental Engineering</option>
<option value="517">Geography</option>
<option value="518">Geology</option>
<option value="519">Geology and Geophysics</option>
<option value="1323">Geomatics Engineering </option>
<option value="522">Geophysics</option>
<option value="523">Geotechical Engineering</option>
<option value="524">German</option>
<option value="525">Global Accounting Practices with Association of International Accounts</option>
<option value="1135">Global Health</option>
<option value="528">Global Logistics and Supply Chain Management</option>
<option value="531">Global Management Accountant Integrated with CIMA, UK + IMA, USA + CMA Australia</option>
<option value="1144">Global studies</option>
<option value="532">Globalisation and Labour</option>
<option value="533">Governance and Public Administration</option>
<option value="534">Graphic Design</option>
<option value="1082">Graphics and mutlimedia</option>
<option value="535">Green Technology</option>
<option value="1353">Ground Water Hydrology</option>
<option value="536">Guidance and Counselling</option>
<option value="537">Health Administration</option>
<option value="1103">Health Care Quality and  Safety</option>
<option value="1124">Health Economics</option>
<option value="1102">Health Economics and  Outcomes Research</option>
<option value="538">Health Policy, Economics and Finance</option>
<option value="541">Heat and Power</option>
<option value="542">Herbal technology</option>
<option value="543">Hindi</option>
<option value="544">History</option>
<option value="545">History and Tourism</option>
<option value="547">Home Science - Clinical Nutrition and Dietetics</option>
<option value="548">Home Science - Nutrition Food Service Management and Dietetics</option>
<option value="550">Horticulture</option>
<option value="1299">Hospital &amp; Health System Management</option>
<option value="1300">Hospital Administration</option>
<option value="552">Hospital and Health Care Management</option>
<option value="553">Hospital Management</option>
<option value="554">Hospitality and Hotel Administration (H. and H.A.)</option>
<option value="555">Hospitality Management</option>
<option value="557">Hotel Management</option>
<option value="558">Hotel Management and Catering Technology (BHM and CT)</option>
<option value="560">Human Development and Family Studies</option>
<option value="561">Human Genetics</option>
<option value="562">Human Genetics and Molecular Biology</option>
<option value="563">Human Physiology</option>
<option value="565">Human Resource Management</option>
<option value="1131">Human resource Management &amp; Industrial Relations</option>
<option value="566">Human Resource Management and Labour Relations</option>
<option value="1127">Humanities</option>
<option value="568">Humanities and Social Sciences</option>
<option value="1324">Hydraulic Engineering</option>
<option value="569">Hydraulics and Water Resource Engineering</option>
<option value="1412">Hydro and Renewable Energy</option>
<option value="1076">Hydrogeology</option>
<option value="1305">Hydrology</option>
<option value="570">I C Technology</option>
<option value="571">Immunology</option>
<option value="573">Inductrial Biotechnology</option>
<option value="575">Industrial and Production</option>
<option value="579">Industrial Biotechnology</option>
<option value="580">Industrial Engineering</option>
<option value="1253">Industrial Engineering &amp; Operation Research</option>
<option value="581">Industrial Engineering and Management</option>
<option value="583">Industrial Metallurgy</option>
<option value="584">Industrial Microbiology</option>
<option value="585">Industrial Pharmacy</option>
<option value="587">Industrial Safety Engineering</option>
<option value="589">Information and Communication Technology</option>
<option value="591">Information and Cyber security</option>
<option value="592">Information Science and Engineering</option>
<option value="593">Information Security</option>
<option value="595">Information Security integrated with KPMG Advanced Certified Cyber Security Professional**</option>
<option value="596">Information System (IS)</option>
<option value="598">Information Technology</option>
<option value="603">Infrastructure Engineering and Management</option>
<option value="1313">Infrastructure Systems</option>
<option value="607">Innovation and Entrepreneurship</option>
<option value="1074">Inorganic Chemistry</option>
<option value="1311">Institute Instrumentation Centre </option>
<option value="609">Instrumentation and Control Engineering</option>
<option value="612">Insurance and Banking Management</option>
<option value="615">Insurance, Banking and Finance</option>
<option value="616">Integrated M. Phil.-Ph. D. Programme in Education</option>
<option value="617">Integrated M. Phil.-Ph. D. Programme in Social Sciences</option>
<option value="618">Integrated M.Phil Ph.D. in Social Sciences with Specialisation in Sociology of Education</option>
<option value="620">Integrated M.Phil-Ph.D programme School of Habitat Studies</option>
<option value="624">Integrated M.Phil.-Ph.D. in Inclusive Development and Social Justice</option>
<option value="1068">Integrated M.Phil.-Ph.D. Programme in Development Studies</option>
<option value="635">Integrated M.Phil.-Ph.D. Programme in Management and Labour Studies</option>
<option value="636">Integrated M.Phil.-Ph.D. Programme in Public Health</option>
<option value="625">Integrated M.Phil.-Ph.D. Programme in Rural Development</option>
<option value="637">Integrated M.Phil.-Ph.D. Programme in Social Work</option>
<option value="638">Integrated M.Phil.-Ph.D. Programme in Women's Studies</option>
<option value="626">Integrated Power System</option>
<option value="628">Intellectual Property Rights</option>
<option value="1406">Intellectual Property Rights and Cyber Law</option>
<option value="1364">Intensive Care Technology</option>
<option value="1380">Interdisciplinary Studies</option>
<option value="639">Interior Design</option>
<option value="640">Interior Design (Honors) with Chartered Institute of Architectural Technologists, UK</option>
<option value="641">Interior Design with Chartered Society of Designers, UK</option>
<option value="642">International Accounting and Finance with ACCA UK integration#</option>
<option value="643">International Banking and Finance</option>
<option value="644">International Business</option>
<option value="646">International Business integrated with Chartered Institute of Marketing, UK</option>
<option value="651">International Law</option>
<option value="652">International Marketing integrated with Digital Marketing Institute, Ireland</option>
<option value="654">International Relations</option>
<option value="657">International Trade and Economic Law</option>
<option value="1277">IOT &amp; Applications</option>
<option value="660">IOT integrated with Foundation Certification in Cloud Technology from Micro Focus (Formerly HPE)</option>
<option value="1333">Irrigation Water Management</option>
<option value="661">Islamic Studies</option>
<option value="662">IT Business Management</option>
<option value="665">Journalism</option>
<option value="666">Journalism and Communication</option>
<option value="667">Journalism and Mass Communication</option>
<option value="1143">Labour Law</option>
<option value="672">Labour Studies and Social Protection</option>
<option value="674">Law</option>
<option value="676">Liberal Arts</option>
<option value="677">Library and Information Science</option>
<option value="678">Life Sciences</option>
<option value="681">Linguistics</option>
<option value="1170">Livelihoods and Social Entrepreneurship</option>
<option value="682">Logistics</option>
<option value="683">Logistics and Supply Chain Management</option>
<option value="684">LSCM+Chartered Institute of Procurement and Supply (CIPS)-UK</option>
<option value="1319">M.Arch</option>
<option value="689">Machine Design</option>
<option value="690">Management</option>
<option value="691">Management Accounting</option>
<option value="692">Management Sciences</option>
<option value="693">Management Studies</option>
<option value="694">Manufacturing and Automation</option>
<option value="695">Manufacturing Engineering</option>
<option value="697">Manufacturing Technology</option>
<option value="1398">Manufacturing Technology &amp; Automation</option>
<option value="698">Marine Engineering</option>
<option value="701">Marketing</option>
<option value="703">Marketing and Finance</option>
<option value="704">Marketing and HR</option>
<option value="705">Marketing and Sales</option>
<option value="706">Mass Communication</option>
<option value="707">Master of Business Administration</option>
<option value="718">Material Science and Technology</option>
<option value="719">Material Science Engineering (MEMS)</option>
<option value="1331">Materials Engineering</option>
<option value="721">Materials Science and Engineering</option>
<option value="722">Materials Science and Metallurgical Engineering</option>
<option value="1133">Maternal &amp; Child Health</option>
<option value="724">Mathematical Sciences</option>
<option value="725">Mathematics</option>
<option value="1201">Mathematics &amp; Applied Statistics and Informatics</option>
<option value="1420">Mathematics &amp; Statistics</option>
<option value="726">Mathematics and Computing</option>
<option value="728">Maths with Computer Application</option>
<option value="734">Mechanical</option>
<option value="1308">Mechanical &amp; Industrial Engineering</option>
<option value="736">Mechanical Engineering</option>
<option value="1392">Mechanical Engineering (Spec. Artificial Intelligence &amp; Machine Learning)</option>
<option value="1400">Mechanical Engineering (Spec. Computer Aided Engineering)</option>
<option value="740">Mechanical Engineering (spec. in Automotive Engineering)</option>
<option value="1393">Mechanical Engineering (Spec. in Electric &amp; Hybrid Vehicles)</option>
<option value="741">Mechanical Engineering (Spec. in Energy Systems)</option>
<option value="1391">Mechanical Engineering (Spec. in Smart Manufacturing)</option>
<option value="1149">Mechanical Engineering (Thermal)</option>
<option value="743">Mechanical Engineering - CAD/CAM</option>
<option value="744">Mechanical Engineering and Manufacturing Engineering</option>
<option value="745">Mechanical Engineering and Mechanical System Design</option>
<option value="746">Mechanical Engineering and Thermal Science and Engineering</option>
<option value="747">Mechanical Engineering Manufacturing Sc. and Engg.</option>
<option value="748">Mechanical Engineering Mechanical systems Design</option>
<option value="1198">Mechanical Engineering with specialisation in Production &amp;  Industrial Engineering</option>
<option value="750">Mechanical System Design(ME)</option>
<option value="1344">Mechanical with specialization in Cyber Physical Systems </option>
<option value="752">Mechatronics</option>
<option value="1346">Mechatronics &amp; Automation </option>
<option value="753">Mechatronics Engineering</option>
<option value="756">Media and Communications</option>
<option value="757">Media and Cultural Studies</option>
<option value="760">Media Studies</option>
<option value="1099">Media Technology</option>
<option value="1130">Medical &amp; Psychiatric Social work</option>
<option value="1269">Medical Anatomy</option>
<option value="1295">Medical Biochemistry</option>
<option value="762">Medical Biotechnology</option>
<option value="763">Medical Electronics</option>
<option value="1087">Medical Imaging Technology</option>
<option value="1086">Medical Lab Technology</option>
<option value="1370">Medical Laboratory Technology (MLT)</option>
<option value="1294">Medical Microbiology</option>
<option value="1270">Medical Pharmacology</option>
<option value="764">Medical Physics</option>
<option value="765">Medical Physiology</option>
<option value="1273">Medical Statistics</option>
<option value="767">Medical Technology</option>
<option value="768">Medicinal and Aromatic Plants</option>
<option value="1171">Mental Health</option>
<option value="769">Metallurgical and Material Science Engineering</option>
<option value="770">Metallurgical and Materials</option>
<option value="771">Metallurgical and Materials Engineering</option>
<option value="772">Metallurgical and Materials Engineering Metal. and Materials Engineering</option>
<option value="773">Metallurgy and Material Science Engineering</option>
<option value="1195">Metallurgy Engineering  and Materials Science</option>
<option value="1190">Metallurgy Engineering and Materials Science with specalisation in Metallurgy Engineering</option>
<option value="1197">Metallurgy Engineering and Materials Science with specialisation in Material Science and Engineering</option>
<option value="776">Microbiology</option>
<option value="777">Microwave and Optical Communication</option>
<option value="778">Mining Engineering</option>
<option value="782">Mobile Applications and Cloud Technology integrated with Foundation Certification in Mobile Application from Micro Focus (Formerly HPE) **</option>
<option value="1297">Molecular Biology</option>
<option value="783">Molecular Biology and biotechnology</option>
<option value="785">Molecular Microbiology</option>
<option value="1108">Molecular Plant Breeding</option>
<option value="786">Multimedia</option>
<option value="787">Multimedia and Animation</option>
<option value="788">Multimedia and Communication</option>
<option value="1339">MURP</option>
<option value="790">Music</option>
<option value="0">NA</option>
<option value="793">Nano Science and Technology</option>
<option value="794">Nano Sciences</option>
<option value="796">Nano Technology</option>
<option value="1070">Nanotechnology</option>
<option value="797">Natural Resource and Governance</option>
<option value="1109">Nematology</option>
<option value="800">Network Engineering</option>
<option value="802">Neural and Cognitive Science</option>
<option value="1359">Neuro Electro Physiology (NEP)</option>
<option value="1094">Neuro-Science Technology</option>
<option value="805">Non- Medical</option>
<option value="807">Nuclear Science and Technology</option>
<option value="809">Nursing</option>
<option value="810">Nutrition</option>
<option value="811">Nutrition and Dietetics</option>
<option value="813">Occupational Therapy</option>
<option value="815">Ocean Engineering and Naval Architecture</option>
<option value="817">Ocean Engineering and Naval Architecutre Ocean Engg. and Naval Arch.</option>
<option value="819">Oils, Oleochemicals and Surfactants Technology</option>
<option value="1266">Operation &amp; Anaesthesia Technology</option>
<option value="820">Operations and Systems</option>
<option value="821">Operations Management</option>
<option value="1268">Optometry</option>
<option value="1361">Optometry (OPT)</option>
<option value="822">Organic Chemistry</option>
<option value="823">Organisation Development, Change and Leadership</option>
<option value="826">Packaging Technology</option>
<option value="828">Painting, Print Making, Sculpture</option>
<option value="1088">Patient Care Management</option>
<option value="829">Peace and Conflict Studies</option>
<option value="1083">Performing Arts</option>
<option value="830">Perfumery and Flavour Technology</option>
<option value="111">Perfusion Technology</option>
<option value="831">Persian</option>
<option value="832">Petroleum Engineering</option>
<option value="1104">Petroleum Technology</option>
<option value="834">Pharmaceutical</option>
<option value="835">Pharmaceutical Analysis</option>
<option value="1283">Pharmaceutical Bio-Technology</option>
<option value="836">Pharmaceutical Chemistry</option>
<option value="837">Pharmaceutical Science and Technology</option>
<option value="838">Pharmaceutical Technology</option>
<option value="839">Pharmaceutics</option>
<option value="840">Pharmacognosy</option>
<option value="1409">Pharmacognosy &amp; Phytochemistry</option>
<option value="841">Pharmacology</option>
<option value="842">Pharmacy</option>
<option value="1289">Pharmacy Administration</option>
<option value="844">Pharmacy Practice</option>
<option value="847">Pharmcology</option>
<option value="848">Philosophy</option>
<option value="850">Photography</option>
<option value="1396">Photography &amp; Cinematography</option>
<option value="1336">Photonics</option>
<option value="1123">Physical Chemistry</option>
<option value="853">Physical Education</option>
<option value="854">Physical Sciences</option>
<option value="1360">Physician Assistant (PA)</option>
<option value="855">Physics</option>
<option value="856">Physics Functional Materials and Devices</option>
<option value="857">Physiology</option>
<option value="858">Physiotherapy</option>
<option value="859">Planning</option>
<option value="860">Plant Biology and Biotechnology</option>
<option value="862">Plant Biology and Plant Technology</option>
<option value="863">Plant Breeding and Genetics</option>
<option value="1115">Plant Nematology</option>
<option value="864">Plant Pathology</option>
<option value="1107">Plant Physiology</option>
<option value="865">Plant Sciences</option>
<option value="1275">Plant Tissue Culture</option>
<option value="866">Plastic Engineering</option>
<option value="1257">Policy Studies</option>
<option value="867">Political Science</option>
<option value="868">Political Science - International Relations</option>
<option value="870">Polymer and Chemical technology</option>
<option value="1317">Polymer and Process Engineering</option>
<option value="871">Polymer Engineering and Technology</option>
<option value="872">Polymer Science and Chemical Technology</option>
<option value="1090">Population Studies</option>
<option value="874">Power and Energy Systems</option>
<option value="875">Power Electronics</option>
<option value="876">Power Electronics and Drives</option>
<option value="877">Power Electronics and Machine Drives</option>
<option value="878">Power Electronics and Power System</option>
<option value="879">Power System Engineerig</option>
<option value="880">Power System Engineering</option>
<option value="881">Power Systems and Automation</option>
<option value="882">PR and Event Management</option>
<option value="1128">Print &amp; Media Technology</option>
<option value="883">Printing Technology</option>
<option value="885">Process Instrumentation</option>
<option value="886">Process Metallurgy</option>
<option value="887">Processing and Food Engineering</option>
<option value="889">Production and Industrial Engineering</option>
<option value="890">Production and Industrial Engineering (ME)</option>
<option value="891">Production Engineering</option>
<option value="892">Production Engineering And Industrial Management</option>
<option value="893">Professional Accounting (PA)</option>
<option value="894">Project Management</option>
<option value="1296">Psychiatric Social Work</option>
<option value="897">Psychology</option>
<option value="898">Public Administration</option>
<option value="899">Public Health</option>
<option value="901">Public Policy and Governance</option>
<option value="1332">Pulp &amp; Paper</option>
<option value="1316">Pulp &amp; Paper Engineering</option>
<option value="904">Quality and Reliability</option>
<option value="906">Quality Assurance</option>
<option value="907">Quality Assurance Techniques</option>
<option value="1280">Quantum Information and Computation</option>
<option value="1097">Radiology</option>
<option value="1279">Regulatory Affairs</option>
<option value="1080">Regulatory Governance</option>
<option value="1369">Remote Sensing &amp; Wireless Sensor Networks</option>
<option value="910">Remote Sensing and Geographic Information Systems</option>
<option value="1292">Renal Dialysis Technology</option>
<option value="1139">Renal Replacement Therapy &amp; Dialysis Technology</option>
<option value="1111">Renewable Energy Engineering</option>
<option value="1250">Resources Engineering</option>
<option value="1291">Respiratory Care Technology</option>
<option value="1140">Respiratory Therapy</option>
<option value="1372">Respiratory Therapy (RPT)</option>
<option value="912">Retail Management</option>
<option value="914">RF and MW</option>
<option value="915">Risk Management with CIMA UK integration #</option>
<option value="916">Robotics</option>
<option value="917">Robotics and Automation</option>
<option value="920">Rural Development</option>
<option value="922">Rural Management</option>
<option value="1089">Sales &amp; Marketing</option>
<option value="927">Sanskrit</option>
<option value="928">Science</option>
<option value="1381">Sciences</option>
<option value="932">Seed Science and Technology</option>
<option value="1327">Seismic Vulnerability and Risk Assessment</option>
<option value="934">Sensor System Technology</option>
<option value="1284">Sensors and Internet of Things</option>
<option value="935">Sericulture</option>
<option value="936">Signal Processing</option>
<option value="937">Signal Processing and Digital Design</option>
<option value="938">Silviculture</option>
<option value="1281">Smart Healthcare</option>
<option value="1290">Smart Manufacturing</option>
<option value="939">Social Entrepreneurship</option>
<option value="941">Social Exclusive and Inclusive Policy</option>
<option value="1176">Social Innovation and Entrepreneurship</option>
<option value="944">Social Science</option>
<option value="949">Social Work</option>
<option value="966">Society and Culture</option>
<option value="967">Sociology</option>
<option value="968">Sociology and Social Anthropology</option>
<option value="969">Software Application Development, Software Testing</option>
<option value="971">Software Engineering</option>
<option value="1263">Software Technology</option>
<option value="972">Soil and Water Engineering</option>
<option value="1325">Soil Dynamics</option>
<option value="973">Soil Science</option>
<option value="1110">Soil Science and Agricultural Chemistry</option>
<option value="974">Solar and Alternative Energy</option>
<option value="1335">Solid State Electronic Materials</option>
<option value="977">South East Asian Studies</option>
<option value="1121">Southeast Asian and Pacific Studies</option>
<option value="1282">Space Technologies</option>
<option value="978">Spanish</option>
<option value="979">Special Education</option>
<option value="1340">Speech Language Pathology</option>
<option value="983">Spices, Plantation, Medicinal and Aromatic Plants</option>
<option value="985">Sports Physiotherapy</option>
<option value="986">Statistics</option>
<option value="987">Statistics with Computer Applications</option>
<option value="989">Storage and Cloud Technology integrated with Advanced Certification in Cloud Technology from Micro Focus (Formerly HPE) **</option>
<option value="1154">Structural and Construction Engineering</option>
<option value="1326">Structural Dynamics</option>
<option value="991">Structural Engineering</option>
<option value="992">Structural Engineering and Disaster Management</option>
<option value="996">Surface Engineering and Technology</option>
<option value="1352">Surface Water Hydrology</option>
<option value="998">Sustainable Architecture</option>
<option value="1175">Sustainable Livelihoods and Natural Resources Governance</option>
<option value="1254">Systems and Control Engineering</option>
<option value="1001">Tamil</option>
<option value="1251">Technology Alternatives</option>
<option value="1003">Telecom Management</option>
<option value="1005">TELECOMMUNICATION ENGINEERING</option>
<option value="1009">Telugu</option>
<option value="1010">Textile Chemistry</option>
<option value="1011">Textile Design</option>
<option value="1012">Textile Engineering</option>
<option value="1155">Textile Engineering and Management</option>
<option value="1013">Textile Technology</option>
<option value="1014">Textiles and Apparel Design</option>
<option value="1073">Theatre Arts</option>
<option value="1016">Thermal and Fluid Science</option>
<option value="1017">Thermal Engineering</option>
<option value="1018">Thermal Power Engineering</option>
<option value="1019">Thermal Science</option>
<option value="1288">Thermofluids Engineering</option>
<option value="1153">Three Subject Combination</option>
<option value="1020">Tourism Administration</option>
<option value="1022">Tourism and Hospitality Management</option>
<option value="1023">Tourism and Hospitality Management integrated with Chartered Institute of Hospitality, UK</option>
<option value="1024">Town and Country planning</option>
<option value="1025">Translation Studies</option>
<option value="1422">Transportation and Infrastructure Engineering</option>
<option value="1026">Transportation Systems Engg</option>
<option value="1027">Travel and Tourism</option>
<option value="1028">Travel and Tourism Management</option>
<option value="1129">Tribology &amp; Maintenance</option>
<option value="1029">Urban Design</option>
<option value="1081">Urban Policy and governance</option>
<option value="1252">Urban Science &amp; Engineering</option>
<option value="1030">Urdu</option>
<option value="1031">Vegetable Science</option>
<option value="1032">Virology</option>
<option value="1064">Visual Arts</option>
<option value="1034">Visual Communication</option>
<option value="1384">Visual Media and Communication</option>
<option value="1036">VLSI</option>
<option value="1037">VLSI and Embedded Systems</option>
<option value="1038">VLSI Design</option>
<option value="1039">VLSI Design and Embedded system</option>
<option value="1164">Water Policy and Governance</option>
<option value="1334">Water Resources Development</option>
<option value="1310">Water Resources Development &amp; Management - Irrigation Water Management</option>
<option value="1309">Water Resources Development &amp; Management - Water Resource Management</option>
<option value="1043">Water Resources Engineering</option>
<option value="1044">Water Resources Engineering and Management</option>
<option value="1045">Watershed Management</option>
<option value="1046">Web Applications</option>
<option value="1047">Welding Engineering</option>
<option value="1051">Wired and Wireless Communication</option>
<option value="1366">Wireless Networks &amp; Applications</option>
<option value="1172">Women-Centred Practice</option>
<option value="1056">Womens Studies</option>
<option value="1058">Wood Science and Technology</option>
<option value="1059">Yoga Therapy</option>
<option value="1060">Zoology</option>
</select>
                    </div>
                </div>
                <div class="col-md-2 col-sm-4 col-xs-12">
                    <div class="form-group institutesDropdown_slider">
                        <label for="sel1" class="white_text">Institute Type:</label>
                        <select class="form-control" id="drpInstituteType" name="InstituteType" required=""><option value="">All</option>
<option value="Private">Private</option>
<option value="Public">Public</option>
</select>
                    </div>
                </div>
                <div class="col-md-1 col-sm-4 col-xs-12">
                    <div class="form-group institutesDropdown_slider">
                        <label for="sel1" class="white_text mb8">&nbsp;</label>
                        <a id="btnSearchInstitute" class="institutesSearch-btn"><i class="fa fa-search"></i></a>
                    </div>
                </div>
            </form>
        </div>
</template>
