<template>
  <div>
    <Head>
      <title> {{ user.full_name }}</title>
    </Head>
    <div class="container pt-100">
      <div class="user_profile_page">
        <div class="row">
          <div class="col-md-8 center-col">
            <div class="row">
              <div class="col-md-3">
                <div class="user_profile_img">
                  <img
                    v-if="user.avatar_url"
                    :src="user.avatar_url"
                    alt=""
                  >
                  <img
                    v-else-if="profile_image_url"
                    :src="profile_image_url"
                    alt=""
                  >
                  <img
                    v-else
                    src="/images/default-avatar.png"
                    alt=""
                  >
                </div>
              </div>
              <div class="col-md-9">
                <div class="user_des">
                  <h3 class="user_profile_name">
                    {{ user.full_name }} <a
                      v-if="user.id===AuthUser.id"
                      href="/account-settings"
                    ><i class="fas fa-edit" /></a>
                  </h3>
                  <button
                    type="button"
                    class="btn-md btn-outline-dark"
                    name="addfollow"
                    @Click="addfollow()"
                  >
                    Follow
                  </button>
                  <p
                    v-if="user.role==='student'"
                    class="text-grey"
                  >
                    Student at
                  </p>
                  <p
                    v-else-if="user.role==='teacher'"
                    class="text-grey"
                  >
                    Teacher at
                  </p>
                  <p
                    v-else-if="user.role==='institute_admin'"
                    class="text-grey"
                  >
                    Admin at
                  </p>
                  <p
                    v-if="user.preferred_institute_name"
                  >
                    {{ user.preferred_institute_name }}
                  </p>
                  <p
                    v-if="user.preferred_course_name"
                  >
                    {{ user.preferred_course_name }}
                  </p>
                </div>
                     
                <div class="mb-2 mt-2">
                  <ul class="social-network social-circle">
                    <li>
                      <a
                        target="_blank"
                        :href="user.insta_url ? ('https://instagram.com/'+user.insta_url) :'#'"
                        :disabled="user.insta_url ? false:true"
                        :class="['icoInstagram', user.insta_url ? '' :'disabled']"
                        title="Instagram"
                      ><i class="fab fa-instagram" /></a>
                    </li>
                    <li>
                      <a
                        target="_blank"
                        :href="user.fb_url ? user.fb_url :'#'"
                        :disabled="user.fb_url ? false:true"
                        :class="['icoFacebook', user.fb_url ? '' :'disabled']"
                        title="Facebook"
                      ><i class="fab fa-facebook-f" /></a>
                    </li>
                    <li>
                      <a
                        :href="user.linkedin_url ? user.linkedin_url :'#'"
                        :disabled="user.linkedin_url ? false:true"
                        target="_blank"
                        :class="['icoLinkedin', user.linkedin_url ? '' :'disabled']"
                        title="Linkedin"
                      ><i class="fab fa-linkedin" /></a>
                    </li>
                    <li>
                      <a
                        target="_blank"
                        :href="user.email ? 'mailto:'+user.email :'#'"
                        :disabled="user.email ? false:true"
                        :class="['icoInstagram', user.email ? '' :'disabled']"
                        title="Email"
                      ><i class="fa fa-envelope" /></a>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </div>



        <nav-tabs
          :tabs="tabs"
          :initial-tab="initialTab"
        >
          <template slot="tab-heading-interests">
            {{ 'Interests' }}
          </template>
          <template slot="tab-panel-interests">
            <div class="user_interest">
              <h4>Your Interest</h4>
              <div class="user_int">
                <div class="user_int_text">
                  <p v-show="user.id===AuthUser.id">
                    This data is generated by your interaction with posts,hence the more you interect with
                    posts the more
                    precise this data is.
                  </p>

                  <div class="row text-center">
                    <div
                      v-for="(interest,index) in interests"
                      :key="index"
                      class="col-md-3 col-6 mb-2"
                      @click="categoryRedirect(interest)"
                    >
                      <radial-progress
                        :value="interest.percent"
                      >
                        <p>{{ parseInt(interest.percent) }}%</p>
                      </radial-progress>
                      <p class="interest_name">
                        {{ interest.name }}
                      </p>
                    </div>
                  </div> 
                </div>
              </div>
            </div>
          </template>
          <template slot="tab-heading-posts">
            {{ 'Posts' }}
          </template>
          <template slot="tab-panel-posts">
            <PostContainer
              :post-route="'/user/'+user.id"
            >
              <template slot="empty">
                Currently no post has been shared.
              </template>
            </PostContainer>
          </template>
          <template slot="tab-heading-doubts">
            {{ 'Doubts' }}
          </template>
          <template slot="tab-panel-doubts">
            <DoubtContainer
              :doubt-route="'/user/'+user.id"
            >
              <template slot="empty">
                Currently no doubt has been shared.
              </template>
            </DoubtContainer>
          </template>
          <template slot="tab-heading-followers">
            {{ 'Followers' }}
          </template>
        </nav-tabs>
      </div>
    </div>
  </div>
</template>
<style>
.interest_name {
  margin-top: 20px;
  margin-right: 50px;
}
@media (max-width: 800px){
    .interest_name {
      margin-right: 0px;
    }
}

h3.user_profile_name span {
    font-size: 14px;
    color: #868686;
    cursor: pointer;
}

h3.user_profile_name {
    display: flex;
    justify-content: space-between;
    align-items: center;
}
button.save_profile_btn {
    border: navajowhite;
    background-color: blue;
    color: white;
    padding: 10px 40px;
    border-radius: 5px;
    margin-top: 10px;
    margin-bottom: 10px;
    font-weight: 500;
    font-size: 16px;
}
button.cancel_profile_btn {
    border: solid 1px #737171;
    background-color: transparent;
    color: black;
    padding: 10px 40px;
    border-radius: 5px;
    margin-top: 10px;
    margin-bottom: 10px;
    font-weight: 500;
    font-size: 16px;
    margin-left: 15px
}
.u_e_img img {
    width: 80px;
    height: 80px;
    border-radius: 50px;
        margin-right: 15px;
}
.user_edit_profile_img {
    display: flex;
    align-items: center;
    margin-bottom: 15px;
}
.user_edit_btn button {
    background-color: blue;
    border: none;
    color: white;
    padding: 5px 8px;
    font-size: 13px;
    border-radius: 5px;
}

.user_edit_btn {
    margin-left: 20px;
}
.user_social_link_left a {
    color: #868686;
}
.edit_profile_head {
    margin-bottom: 20px;
    border-bottom: solid 1px #ccc;
    margin-top: 10px;
}
.v--modal-box.v--modal {
    top: 130px !important;
}
.edit_img_btn {
    /* border: solid 1px #ccc; */
    padding: 8px;
    border-radius: 4px;
    background: #f0f0f0;
    cursor: pointer;
}
.sh_kn {
    margin-top: 30px;
    background: #F4F4F4 ;
    text-align: center;
    padding: 40px;
    box-shadow: 0 0 10px rgba(0,0,0,0.12);
    border-radius: 4px;
}
.sh_kn a {
    border: solid 1px #3746C5;
    padding: 10px 30px;
    margin-top: 8px;
    display: inline-block;
    border-radius: 1px;
}

.sh_kn h4 {
    color: black;
    margin: 20px 0;
}
</style>
<script>
import RadialProgress from '@/components/RadialProgress';
import NavTabs from '@/components/NavTabs.vue';
import PostContainer from '@/Pages/common/post-container.vue';
import DoubtContainer from '@/Pages/doubt/doubt-container.vue';

export default {
	components: {
		NavTabs,
		PostContainer,
		DoubtContainer,
		RadialProgress
	},
	props: ['user'],
	data() {
		return {
			interests: [],
			initialTab:'interests',
			tabs:['interests','posts','doubts'],
			interest_enable: false,
			image:'',
			profile_image_url:'',
			errors:{
				intro: '',
				profile_pic: '',
				fb_url: '',
				insta_url: '',
				linked_url: '',
			},
			profile_data: {
				profile_pic: '',
				intro: '',
				fb_url: '',
				insta_url: '',
				linked_url: '',
			}
		};

	},
	watch: {
		user(val) {
			this.setProfile(val);
		}
	},
	mounted() {
		this.axios.get('/api/get-profile').then((resp) => {
			let total = 0;
			this.interests = resp.data.success.interests.map(node=>{
				node.total=node.total_views+(node.total_likes*3)+(node.total_posts*7);
				total += node.total;
				return node;
			}).map(node=>{
				node.percent=total>0 ? parseInt((node.total/total)*100) : 0;
				return node;
			})
				.sort((a,b)=>a.percent>b.percent ? -1 : 1);
		});
	},

	methods:
      {
      	addfollow()
      	{
      		this.axios.post('/api/addfollow/'+this.postContent.id+'/follow').catch(err => {
      			this.follow_active = !this.follow_active;
		  	});      
      	}

      }
};

</script>